/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * NTI Backend
 * API for NTI platform workflows, authentication, and administrative operations.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AdminUniversityEmailDomainsControllerListParams,
  CreateUniversityEmailDomainDto,
  RejectUniversityEmailDomainDto
} from '../index.schemas';

import { orvalMutator } from '../../api-client/openapi-runtime/runtime';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const adminUniversityEmailDomainsControllerList = (
    params?: AdminUniversityEmailDomainsControllerListParams,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<void>(
      {url: `/admin/university-email-domains`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getAdminUniversityEmailDomainsControllerListQueryKey = (params?: AdminUniversityEmailDomainsControllerListParams,) => {
    return [
    `/admin/university-email-domains`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getAdminUniversityEmailDomainsControllerListQueryOptions = <TData = Awaited<ReturnType<typeof adminUniversityEmailDomainsControllerList>>, TError = unknown>(params?: AdminUniversityEmailDomainsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminUniversityEmailDomainsControllerList>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminUniversityEmailDomainsControllerListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminUniversityEmailDomainsControllerList>>> = ({ signal }) => adminUniversityEmailDomainsControllerList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminUniversityEmailDomainsControllerList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminUniversityEmailDomainsControllerListQueryResult = NonNullable<Awaited<ReturnType<typeof adminUniversityEmailDomainsControllerList>>>
export type AdminUniversityEmailDomainsControllerListQueryError = unknown


export function useAdminUniversityEmailDomainsControllerList<TData = Awaited<ReturnType<typeof adminUniversityEmailDomainsControllerList>>, TError = unknown>(
 params: undefined |  AdminUniversityEmailDomainsControllerListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminUniversityEmailDomainsControllerList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminUniversityEmailDomainsControllerList>>,
          TError,
          Awaited<ReturnType<typeof adminUniversityEmailDomainsControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminUniversityEmailDomainsControllerList<TData = Awaited<ReturnType<typeof adminUniversityEmailDomainsControllerList>>, TError = unknown>(
 params?: AdminUniversityEmailDomainsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminUniversityEmailDomainsControllerList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminUniversityEmailDomainsControllerList>>,
          TError,
          Awaited<ReturnType<typeof adminUniversityEmailDomainsControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminUniversityEmailDomainsControllerList<TData = Awaited<ReturnType<typeof adminUniversityEmailDomainsControllerList>>, TError = unknown>(
 params?: AdminUniversityEmailDomainsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminUniversityEmailDomainsControllerList>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAdminUniversityEmailDomainsControllerList<TData = Awaited<ReturnType<typeof adminUniversityEmailDomainsControllerList>>, TError = unknown>(
 params?: AdminUniversityEmailDomainsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminUniversityEmailDomainsControllerList>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminUniversityEmailDomainsControllerListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const adminUniversityEmailDomainsControllerCreate = (
    createUniversityEmailDomainDto: CreateUniversityEmailDomainDto,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<void>(
      {url: `/admin/university-email-domains`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createUniversityEmailDomainDto, signal
    },
      options);
    }
  


export const getAdminUniversityEmailDomainsControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUniversityEmailDomainsControllerCreate>>, TError,{data: CreateUniversityEmailDomainDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof adminUniversityEmailDomainsControllerCreate>>, TError,{data: CreateUniversityEmailDomainDto}, TContext> => {

const mutationKey = ['adminUniversityEmailDomainsControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminUniversityEmailDomainsControllerCreate>>, {data: CreateUniversityEmailDomainDto}> = (props) => {
          const {data} = props ?? {};

          return  adminUniversityEmailDomainsControllerCreate(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AdminUniversityEmailDomainsControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof adminUniversityEmailDomainsControllerCreate>>>
    export type AdminUniversityEmailDomainsControllerCreateMutationBody = CreateUniversityEmailDomainDto
    export type AdminUniversityEmailDomainsControllerCreateMutationError = unknown

    export const useAdminUniversityEmailDomainsControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUniversityEmailDomainsControllerCreate>>, TError,{data: CreateUniversityEmailDomainDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminUniversityEmailDomainsControllerCreate>>,
        TError,
        {data: CreateUniversityEmailDomainDto},
        TContext
      > => {

      const mutationOptions = getAdminUniversityEmailDomainsControllerCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const adminUniversityEmailDomainsControllerApprove = (
    id: string,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<void>(
      {url: `/admin/university-email-domains/${id}/approve`, method: 'POST', signal
    },
      options);
    }
  


export const getAdminUniversityEmailDomainsControllerApproveMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUniversityEmailDomainsControllerApprove>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof adminUniversityEmailDomainsControllerApprove>>, TError,{id: string}, TContext> => {

const mutationKey = ['adminUniversityEmailDomainsControllerApprove'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminUniversityEmailDomainsControllerApprove>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  adminUniversityEmailDomainsControllerApprove(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AdminUniversityEmailDomainsControllerApproveMutationResult = NonNullable<Awaited<ReturnType<typeof adminUniversityEmailDomainsControllerApprove>>>
    
    export type AdminUniversityEmailDomainsControllerApproveMutationError = unknown

    export const useAdminUniversityEmailDomainsControllerApprove = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUniversityEmailDomainsControllerApprove>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminUniversityEmailDomainsControllerApprove>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getAdminUniversityEmailDomainsControllerApproveMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const adminUniversityEmailDomainsControllerReject = (
    id: string,
    rejectUniversityEmailDomainDto: RejectUniversityEmailDomainDto,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<void>(
      {url: `/admin/university-email-domains/${id}/reject`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: rejectUniversityEmailDomainDto, signal
    },
      options);
    }
  


export const getAdminUniversityEmailDomainsControllerRejectMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUniversityEmailDomainsControllerReject>>, TError,{id: string;data: RejectUniversityEmailDomainDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof adminUniversityEmailDomainsControllerReject>>, TError,{id: string;data: RejectUniversityEmailDomainDto}, TContext> => {

const mutationKey = ['adminUniversityEmailDomainsControllerReject'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminUniversityEmailDomainsControllerReject>>, {id: string;data: RejectUniversityEmailDomainDto}> = (props) => {
          const {id,data} = props ?? {};

          return  adminUniversityEmailDomainsControllerReject(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AdminUniversityEmailDomainsControllerRejectMutationResult = NonNullable<Awaited<ReturnType<typeof adminUniversityEmailDomainsControllerReject>>>
    export type AdminUniversityEmailDomainsControllerRejectMutationBody = RejectUniversityEmailDomainDto
    export type AdminUniversityEmailDomainsControllerRejectMutationError = unknown

    export const useAdminUniversityEmailDomainsControllerReject = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUniversityEmailDomainsControllerReject>>, TError,{id: string;data: RejectUniversityEmailDomainDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminUniversityEmailDomainsControllerReject>>,
        TError,
        {id: string;data: RejectUniversityEmailDomainDto},
        TContext
      > => {

      const mutationOptions = getAdminUniversityEmailDomainsControllerRejectMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const adminUniversityEmailDomainsControllerRemove = (
    id: string,
 options?: SecondParameter<typeof orvalMutator>,) => {
      
      
      return orvalMutator<void>(
      {url: `/admin/university-email-domains/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getAdminUniversityEmailDomainsControllerRemoveMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUniversityEmailDomainsControllerRemove>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof adminUniversityEmailDomainsControllerRemove>>, TError,{id: string}, TContext> => {

const mutationKey = ['adminUniversityEmailDomainsControllerRemove'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminUniversityEmailDomainsControllerRemove>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  adminUniversityEmailDomainsControllerRemove(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AdminUniversityEmailDomainsControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof adminUniversityEmailDomainsControllerRemove>>>
    
    export type AdminUniversityEmailDomainsControllerRemoveMutationError = unknown

    export const useAdminUniversityEmailDomainsControllerRemove = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUniversityEmailDomainsControllerRemove>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminUniversityEmailDomainsControllerRemove>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getAdminUniversityEmailDomainsControllerRemoveMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    