/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * NTI Backend
 * API for NTI platform workflows, authentication, and administrative operations.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AdminListOrganizationsParams,
  AdminOrganizationResponseDto,
  ListOrganizationsResponseDto,
  OrganizationInviteItemDto,
  OrganizationStatusResponseDto,
  UpdateOrgStatusDto
} from '../index.schemas';

import { orvalMutator } from '../../api-client/openapi-runtime/runtime';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns a paginated, filterable, and sortable list of all organizations for administrators.
 * @summary List organizations (admin)
 */
export const adminListOrganizations = (
    params?: AdminListOrganizationsParams,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<ListOrganizationsResponseDto>(
      {url: `/admin/organizations`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getAdminListOrganizationsQueryKey = (params?: AdminListOrganizationsParams,) => {
    return [
    `/admin/organizations`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getAdminListOrganizationsQueryOptions = <TData = Awaited<ReturnType<typeof adminListOrganizations>>, TError = void>(params?: AdminListOrganizationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListOrganizations>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminListOrganizationsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminListOrganizations>>> = ({ signal }) => adminListOrganizations(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminListOrganizations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminListOrganizationsQueryResult = NonNullable<Awaited<ReturnType<typeof adminListOrganizations>>>
export type AdminListOrganizationsQueryError = void


export function useAdminListOrganizations<TData = Awaited<ReturnType<typeof adminListOrganizations>>, TError = void>(
 params: undefined |  AdminListOrganizationsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListOrganizations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListOrganizations>>,
          TError,
          Awaited<ReturnType<typeof adminListOrganizations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListOrganizations<TData = Awaited<ReturnType<typeof adminListOrganizations>>, TError = void>(
 params?: AdminListOrganizationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListOrganizations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListOrganizations>>,
          TError,
          Awaited<ReturnType<typeof adminListOrganizations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListOrganizations<TData = Awaited<ReturnType<typeof adminListOrganizations>>, TError = void>(
 params?: AdminListOrganizationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListOrganizations>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List organizations (admin)
 */

export function useAdminListOrganizations<TData = Awaited<ReturnType<typeof adminListOrganizations>>, TError = void>(
 params?: AdminListOrganizationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListOrganizations>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminListOrganizationsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Returns organization profile by id for administrators, including the single company owner summary.
 * @summary Get organization (admin)
 */
export const adminGetOrganization = (
    id: string,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<AdminOrganizationResponseDto>(
      {url: `/admin/organizations/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getAdminGetOrganizationQueryKey = (id?: string,) => {
    return [
    `/admin/organizations/${id}`
    ] as const;
    }

    
export const getAdminGetOrganizationQueryOptions = <TData = Awaited<ReturnType<typeof adminGetOrganization>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetOrganization>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminGetOrganizationQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminGetOrganization>>> = ({ signal }) => adminGetOrganization(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminGetOrganization>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminGetOrganizationQueryResult = NonNullable<Awaited<ReturnType<typeof adminGetOrganization>>>
export type AdminGetOrganizationQueryError = void


export function useAdminGetOrganization<TData = Awaited<ReturnType<typeof adminGetOrganization>>, TError = void>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetOrganization>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetOrganization>>,
          TError,
          Awaited<ReturnType<typeof adminGetOrganization>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminGetOrganization<TData = Awaited<ReturnType<typeof adminGetOrganization>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetOrganization>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetOrganization>>,
          TError,
          Awaited<ReturnType<typeof adminGetOrganization>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminGetOrganization<TData = Awaited<ReturnType<typeof adminGetOrganization>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetOrganization>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get organization (admin)
 */

export function useAdminGetOrganization<TData = Awaited<ReturnType<typeof adminGetOrganization>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetOrganization>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminGetOrganizationQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Allows ADMIN and SUPER_ADMIN to approve or reject organizations that are pending review.
 * @summary Process organization status
 */
export const adminUpdateOrganizationStatus = (
    id: string,
    updateOrgStatusDto: UpdateOrgStatusDto,
 options?: SecondParameter<typeof orvalMutator>,) => {
      
      
      return orvalMutator<OrganizationStatusResponseDto>(
      {url: `/admin/organizations/${id}/status`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateOrgStatusDto
    },
      options);
    }
  


export const getAdminUpdateOrganizationStatusMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateOrganizationStatus>>, TError,{id: string;data: UpdateOrgStatusDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof adminUpdateOrganizationStatus>>, TError,{id: string;data: UpdateOrgStatusDto}, TContext> => {

const mutationKey = ['adminUpdateOrganizationStatus'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminUpdateOrganizationStatus>>, {id: string;data: UpdateOrgStatusDto}> = (props) => {
          const {id,data} = props ?? {};

          return  adminUpdateOrganizationStatus(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AdminUpdateOrganizationStatusMutationResult = NonNullable<Awaited<ReturnType<typeof adminUpdateOrganizationStatus>>>
    export type AdminUpdateOrganizationStatusMutationBody = UpdateOrgStatusDto
    export type AdminUpdateOrganizationStatusMutationError = void

    /**
 * @summary Process organization status
 */
export const useAdminUpdateOrganizationStatus = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateOrganizationStatus>>, TError,{id: string;data: UpdateOrgStatusDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminUpdateOrganizationStatus>>,
        TError,
        {id: string;data: UpdateOrgStatusDto},
        TContext
      > => {

      const mutationOptions = getAdminUpdateOrganizationStatusMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Returns organization invite records across all organizations for ADMIN and SUPER_ADMIN.
 * @summary List organization invites
 */
export const adminListOrganizationInvites = (
    
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<OrganizationInviteItemDto[]>(
      {url: `/admin/organizations/invites`, method: 'GET', signal
    },
      options);
    }
  



export const getAdminListOrganizationInvitesQueryKey = () => {
    return [
    `/admin/organizations/invites`
    ] as const;
    }

    
export const getAdminListOrganizationInvitesQueryOptions = <TData = Awaited<ReturnType<typeof adminListOrganizationInvites>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListOrganizationInvites>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminListOrganizationInvitesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminListOrganizationInvites>>> = ({ signal }) => adminListOrganizationInvites(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminListOrganizationInvites>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminListOrganizationInvitesQueryResult = NonNullable<Awaited<ReturnType<typeof adminListOrganizationInvites>>>
export type AdminListOrganizationInvitesQueryError = void


export function useAdminListOrganizationInvites<TData = Awaited<ReturnType<typeof adminListOrganizationInvites>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListOrganizationInvites>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListOrganizationInvites>>,
          TError,
          Awaited<ReturnType<typeof adminListOrganizationInvites>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListOrganizationInvites<TData = Awaited<ReturnType<typeof adminListOrganizationInvites>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListOrganizationInvites>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListOrganizationInvites>>,
          TError,
          Awaited<ReturnType<typeof adminListOrganizationInvites>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListOrganizationInvites<TData = Awaited<ReturnType<typeof adminListOrganizationInvites>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListOrganizationInvites>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List organization invites
 */

export function useAdminListOrganizationInvites<TData = Awaited<ReturnType<typeof adminListOrganizationInvites>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListOrganizationInvites>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminListOrganizationInvitesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Returns organization invite records for a specific organization id for ADMIN and SUPER_ADMIN.
 * @summary List organization invites by organization
 */
export const adminListOrganizationInvitesByOrganization = (
    id: string,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<OrganizationInviteItemDto[]>(
      {url: `/admin/organizations/${id}/invites`, method: 'GET', signal
    },
      options);
    }
  



export const getAdminListOrganizationInvitesByOrganizationQueryKey = (id?: string,) => {
    return [
    `/admin/organizations/${id}/invites`
    ] as const;
    }

    
export const getAdminListOrganizationInvitesByOrganizationQueryOptions = <TData = Awaited<ReturnType<typeof adminListOrganizationInvitesByOrganization>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListOrganizationInvitesByOrganization>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminListOrganizationInvitesByOrganizationQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminListOrganizationInvitesByOrganization>>> = ({ signal }) => adminListOrganizationInvitesByOrganization(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminListOrganizationInvitesByOrganization>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminListOrganizationInvitesByOrganizationQueryResult = NonNullable<Awaited<ReturnType<typeof adminListOrganizationInvitesByOrganization>>>
export type AdminListOrganizationInvitesByOrganizationQueryError = void


export function useAdminListOrganizationInvitesByOrganization<TData = Awaited<ReturnType<typeof adminListOrganizationInvitesByOrganization>>, TError = void>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListOrganizationInvitesByOrganization>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListOrganizationInvitesByOrganization>>,
          TError,
          Awaited<ReturnType<typeof adminListOrganizationInvitesByOrganization>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListOrganizationInvitesByOrganization<TData = Awaited<ReturnType<typeof adminListOrganizationInvitesByOrganization>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListOrganizationInvitesByOrganization>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListOrganizationInvitesByOrganization>>,
          TError,
          Awaited<ReturnType<typeof adminListOrganizationInvitesByOrganization>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListOrganizationInvitesByOrganization<TData = Awaited<ReturnType<typeof adminListOrganizationInvitesByOrganization>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListOrganizationInvitesByOrganization>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List organization invites by organization
 */

export function useAdminListOrganizationInvitesByOrganization<TData = Awaited<ReturnType<typeof adminListOrganizationInvitesByOrganization>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListOrganizationInvitesByOrganization>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminListOrganizationInvitesByOrganizationQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




