/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * NTI Backend
 * API for NTI platform workflows, authentication, and administrative operations.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AcceptInviteOrgDto,
  AdminLoginResponseDto,
  AuthResponseDto,
  AuthenticatedUserDto,
  ConfirmEmailDto,
  ForceChangePasswordDto,
  ForgotPasswordDto,
  LoginDto,
  LogoutResponseDto,
  MessageResponseDto,
  RegisterCompanyOwnerDto,
  RegisterDto,
  RegisterViaInviteDto,
  ResendEmailDto,
  ResetPasswordDto
} from '../index.schemas';

import { orvalMutator } from '../../api-client/openapi-runtime/runtime';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Creates a new account, sends an email verification link, and returns the authenticated user context. The account will be created with a pending status until the email is confirmed.
 * @summary Register a new user
 */
export const register = (
    registerDto: RegisterDto,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<AuthenticatedUserDto>(
      {url: `/auth/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerDto, signal
    },
      options);
    }
  


export const getRegisterMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: RegisterDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: RegisterDto}, TContext> => {

const mutationKey = ['register'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof register>>, {data: RegisterDto}> = (props) => {
          const {data} = props ?? {};

          return  register(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RegisterMutationResult = NonNullable<Awaited<ReturnType<typeof register>>>
    export type RegisterMutationBody = RegisterDto
    export type RegisterMutationError = void

    /**
 * @summary Register a new user
 */
export const useRegister = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: RegisterDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof register>>,
        TError,
        {data: RegisterDto},
        TContext
      > => {

      const mutationOptions = getRegisterMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Creates a new account, sends an email verification link, and returns the authenticated user context. The account will be created with a pending status until the email is confirmed.
 * @summary Register a new company owner
 */
export const registerCompanyOwner = (
    registerCompanyOwnerDto: RegisterCompanyOwnerDto,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<AuthenticatedUserDto>(
      {url: `/auth/register-company-owner`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerCompanyOwnerDto, signal
    },
      options);
    }
  


export const getRegisterCompanyOwnerMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerCompanyOwner>>, TError,{data: RegisterCompanyOwnerDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof registerCompanyOwner>>, TError,{data: RegisterCompanyOwnerDto}, TContext> => {

const mutationKey = ['registerCompanyOwner'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof registerCompanyOwner>>, {data: RegisterCompanyOwnerDto}> = (props) => {
          const {data} = props ?? {};

          return  registerCompanyOwner(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RegisterCompanyOwnerMutationResult = NonNullable<Awaited<ReturnType<typeof registerCompanyOwner>>>
    export type RegisterCompanyOwnerMutationBody = RegisterCompanyOwnerDto
    export type RegisterCompanyOwnerMutationError = void

    /**
 * @summary Register a new company owner
 */
export const useRegisterCompanyOwner = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerCompanyOwner>>, TError,{data: RegisterCompanyOwnerDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof registerCompanyOwner>>,
        TError,
        {data: RegisterCompanyOwnerDto},
        TContext
      > => {

      const mutationOptions = getRegisterCompanyOwnerMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Creates an active user account from a valid team invitation token, joins the invited team, marks the invitation as accepted, and issues auth cookies.
 * @summary Register via invite
 */
export const registerViaInvite = (
    registerViaInviteDto: RegisterViaInviteDto,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<AuthResponseDto>(
      {url: `/auth/register-via-invite`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerViaInviteDto, signal
    },
      options);
    }
  


export const getRegisterViaInviteMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerViaInvite>>, TError,{data: RegisterViaInviteDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof registerViaInvite>>, TError,{data: RegisterViaInviteDto}, TContext> => {

const mutationKey = ['registerViaInvite'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof registerViaInvite>>, {data: RegisterViaInviteDto}> = (props) => {
          const {data} = props ?? {};

          return  registerViaInvite(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RegisterViaInviteMutationResult = NonNullable<Awaited<ReturnType<typeof registerViaInvite>>>
    export type RegisterViaInviteMutationBody = RegisterViaInviteDto
    export type RegisterViaInviteMutationError = void

    /**
 * @summary Register via invite
 */
export const useRegisterViaInvite = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerViaInvite>>, TError,{data: RegisterViaInviteDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof registerViaInvite>>,
        TError,
        {data: RegisterViaInviteDto},
        TContext
      > => {

      const mutationOptions = getRegisterViaInviteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Authenticates non-admin users and writes both access and refresh tokens into HttpOnly cookies. Admin accounts must use `/auth/admin/login`.
 * @summary Log in
 */
export const login = (
    loginDto: LoginDto,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<AuthResponseDto>(
      {url: `/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginDto, signal
    },
      options);
    }
  


export const getLoginMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginDto}, TContext> => {

const mutationKey = ['login'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof login>>, {data: LoginDto}> = (props) => {
          const {data} = props ?? {};

          return  login(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>
    export type LoginMutationBody = LoginDto
    export type LoginMutationError = void

    /**
 * @summary Log in
 */
export const useLogin = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof login>>,
        TError,
        {data: LoginDto},
        TContext
      > => {

      const mutationOptions = getLoginMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Creates a new company employee account from a valid organization invitation token. The user receives access and refresh tokens via HttpOnly cookies.
 * @summary Accept organization invitation
 */
export const acceptOrganizationInvite = (
    acceptInviteOrgDto: AcceptInviteOrgDto,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<AuthResponseDto>(
      {url: `/auth/join-company`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: acceptInviteOrgDto, signal
    },
      options);
    }
  


export const getAcceptOrganizationInviteMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof acceptOrganizationInvite>>, TError,{data: AcceptInviteOrgDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof acceptOrganizationInvite>>, TError,{data: AcceptInviteOrgDto}, TContext> => {

const mutationKey = ['acceptOrganizationInvite'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof acceptOrganizationInvite>>, {data: AcceptInviteOrgDto}> = (props) => {
          const {data} = props ?? {};

          return  acceptOrganizationInvite(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AcceptOrganizationInviteMutationResult = NonNullable<Awaited<ReturnType<typeof acceptOrganizationInvite>>>
    export type AcceptOrganizationInviteMutationBody = AcceptInviteOrgDto
    export type AcceptOrganizationInviteMutationError = void

    /**
 * @summary Accept organization invitation
 */
export const useAcceptOrganizationInvite = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof acceptOrganizationInvite>>, TError,{data: AcceptInviteOrgDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof acceptOrganizationInvite>>,
        TError,
        {data: AcceptInviteOrgDto},
        TContext
      > => {

      const mutationOptions = getAcceptOrganizationInviteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Authenticates ADMIN or SUPER_ADMIN accounts. If password rotation is required, returns `requiresPasswordChange=true` and sets short-lived HttpOnly `requiresPasswordChangeToken` cookie instead of issuing session tokens.
 * @summary Log in as admin
 */
export const adminLogin = (
    loginDto: LoginDto,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<AdminLoginResponseDto>(
      {url: `/auth/admin/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginDto, signal
    },
      options);
    }
  


export const getAdminLoginMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminLogin>>, TError,{data: LoginDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof adminLogin>>, TError,{data: LoginDto}, TContext> => {

const mutationKey = ['adminLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminLogin>>, {data: LoginDto}> = (props) => {
          const {data} = props ?? {};

          return  adminLogin(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AdminLoginMutationResult = NonNullable<Awaited<ReturnType<typeof adminLogin>>>
    export type AdminLoginMutationBody = LoginDto
    export type AdminLoginMutationError = void

    /**
 * @summary Log in as admin
 */
export const useAdminLogin = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminLogin>>, TError,{data: LoginDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminLogin>>,
        TError,
        {data: LoginDto},
        TContext
      > => {

      const mutationOptions = getAdminLoginMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Validates a short-lived password-change challenge token from HttpOnly `requiresPasswordChangeToken` cookie, updates password hash, clears forced-change flag, and issues normal auth tokens.
 * @summary Force change password
 */
export const adminForceChangePassword = (
    forceChangePasswordDto: ForceChangePasswordDto,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<AuthResponseDto>(
      {url: `/auth/admin/force-change-password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: forceChangePasswordDto, signal
    },
      options);
    }
  


export const getAdminForceChangePasswordMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminForceChangePassword>>, TError,{data: ForceChangePasswordDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof adminForceChangePassword>>, TError,{data: ForceChangePasswordDto}, TContext> => {

const mutationKey = ['adminForceChangePassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminForceChangePassword>>, {data: ForceChangePasswordDto}> = (props) => {
          const {data} = props ?? {};

          return  adminForceChangePassword(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AdminForceChangePasswordMutationResult = NonNullable<Awaited<ReturnType<typeof adminForceChangePassword>>>
    export type AdminForceChangePasswordMutationBody = ForceChangePasswordDto
    export type AdminForceChangePasswordMutationError = void

    /**
 * @summary Force change password
 */
export const useAdminForceChangePassword = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminForceChangePassword>>, TError,{data: ForceChangePasswordDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminForceChangePassword>>,
        TError,
        {data: ForceChangePasswordDto},
        TContext
      > => {

      const mutationOptions = getAdminForceChangePasswordMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Returns the current authenticated user using the `accessToken` cookie (or Bearer token for backward compatibility).
 * @summary Get current user
 */
export const getMe = (
    
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<AuthenticatedUserDto>(
      {url: `/auth/me`, method: 'GET', signal
    },
      options);
    }
  



export const getGetMeQueryKey = () => {
    return [
    `/auth/me`
    ] as const;
    }

    
export const getGetMeQueryOptions = <TData = Awaited<ReturnType<typeof getMe>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({ signal }) => getMe(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>
export type GetMeQueryError = void


export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get current user
 */

export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Uses the HttpOnly `refreshToken` cookie to rotate the refresh token and issue a new `accessToken` cookie.
 * @summary Refresh access token
 */
export const refreshSession = (
    
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<AuthResponseDto>(
      {url: `/auth/refresh`, method: 'POST', signal
    },
      options);
    }
  


export const getRefreshSessionMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refreshSession>>, TError,void, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof refreshSession>>, TError,void, TContext> => {

const mutationKey = ['refreshSession'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof refreshSession>>, void> = () => {
          

          return  refreshSession(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RefreshSessionMutationResult = NonNullable<Awaited<ReturnType<typeof refreshSession>>>
    
    export type RefreshSessionMutationError = void

    /**
 * @summary Refresh access token
 */
export const useRefreshSession = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refreshSession>>, TError,void, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof refreshSession>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getRefreshSessionMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Revokes the current refresh token and clears `accessToken` and `refreshToken` cookies.
 * @summary Log out
 */
export const logout = (
    
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<LogoutResponseDto>(
      {url: `/auth/logout`, method: 'POST', signal
    },
      options);
    }
  


export const getLogoutMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,void, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,void, TContext> => {

const mutationKey = ['logout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logout>>, void> = () => {
          

          return  logout(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LogoutMutationResult = NonNullable<Awaited<ReturnType<typeof logout>>>
    
    export type LogoutMutationError = void

    /**
 * @summary Log out
 */
export const useLogout = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,void, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof logout>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getLogoutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Confirms the user's email address using the verification token.
 * @summary Confirm email
 */
export const confirmEmail = (
    confirmEmailDto: ConfirmEmailDto,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<AuthResponseDto>(
      {url: `/auth/confirm-email`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: confirmEmailDto, signal
    },
      options);
    }
  


export const getConfirmEmailMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof confirmEmail>>, TError,{data: ConfirmEmailDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof confirmEmail>>, TError,{data: ConfirmEmailDto}, TContext> => {

const mutationKey = ['confirmEmail'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof confirmEmail>>, {data: ConfirmEmailDto}> = (props) => {
          const {data} = props ?? {};

          return  confirmEmail(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ConfirmEmailMutationResult = NonNullable<Awaited<ReturnType<typeof confirmEmail>>>
    export type ConfirmEmailMutationBody = ConfirmEmailDto
    export type ConfirmEmailMutationError = void

    /**
 * @summary Confirm email
 */
export const useConfirmEmail = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof confirmEmail>>, TError,{data: ConfirmEmailDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof confirmEmail>>,
        TError,
        {data: ConfirmEmailDto},
        TContext
      > => {

      const mutationOptions = getConfirmEmailMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Sends a new email verification token to the specified email address.
 * @summary Resend confirmation email
 */
export const resendConfirmationEmail = (
    resendEmailDto: ResendEmailDto,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<void>(
      {url: `/auth/resend-confirmation-email`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: resendEmailDto, signal
    },
      options);
    }
  


export const getResendConfirmationEmailMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resendConfirmationEmail>>, TError,{data: ResendEmailDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof resendConfirmationEmail>>, TError,{data: ResendEmailDto}, TContext> => {

const mutationKey = ['resendConfirmationEmail'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof resendConfirmationEmail>>, {data: ResendEmailDto}> = (props) => {
          const {data} = props ?? {};

          return  resendConfirmationEmail(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ResendConfirmationEmailMutationResult = NonNullable<Awaited<ReturnType<typeof resendConfirmationEmail>>>
    export type ResendConfirmationEmailMutationBody = ResendEmailDto
    export type ResendConfirmationEmailMutationError = unknown

    /**
 * @summary Resend confirmation email
 */
export const useResendConfirmationEmail = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resendConfirmationEmail>>, TError,{data: ResendEmailDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof resendConfirmationEmail>>,
        TError,
        {data: ResendEmailDto},
        TContext
      > => {

      const mutationOptions = getResendConfirmationEmailMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Accepts an email address and, if the account exists, enqueues a password reset email without revealing whether the email is registered.
 * @summary Request password reset
 */
export const forgotPassword = (
    forgotPasswordDto: ForgotPasswordDto,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<MessageResponseDto>(
      {url: `/auth/forgot-password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: forgotPasswordDto, signal
    },
      options);
    }
  


export const getForgotPasswordMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof forgotPassword>>, TError,{data: ForgotPasswordDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof forgotPassword>>, TError,{data: ForgotPasswordDto}, TContext> => {

const mutationKey = ['forgotPassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof forgotPassword>>, {data: ForgotPasswordDto}> = (props) => {
          const {data} = props ?? {};

          return  forgotPassword(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ForgotPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof forgotPassword>>>
    export type ForgotPasswordMutationBody = ForgotPasswordDto
    export type ForgotPasswordMutationError = unknown

    /**
 * @summary Request password reset
 */
export const useForgotPassword = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof forgotPassword>>, TError,{data: ForgotPasswordDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof forgotPassword>>,
        TError,
        {data: ForgotPasswordDto},
        TContext
      > => {

      const mutationOptions = getForgotPasswordMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Resets the account password using a valid password reset token and revokes all active refresh tokens for the user.
 * @summary Reset password
 */
export const resetPassword = (
    resetPasswordDto: ResetPasswordDto,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<MessageResponseDto>(
      {url: `/auth/reset-password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: resetPasswordDto, signal
    },
      options);
    }
  


export const getResetPasswordMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resetPassword>>, TError,{data: ResetPasswordDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof resetPassword>>, TError,{data: ResetPasswordDto}, TContext> => {

const mutationKey = ['resetPassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof resetPassword>>, {data: ResetPasswordDto}> = (props) => {
          const {data} = props ?? {};

          return  resetPassword(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ResetPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof resetPassword>>>
    export type ResetPasswordMutationBody = ResetPasswordDto
    export type ResetPasswordMutationError = void

    /**
 * @summary Reset password
 */
export const useResetPassword = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resetPassword>>, TError,{data: ResetPasswordDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof resetPassword>>,
        TError,
        {data: ResetPasswordDto},
        TContext
      > => {

      const mutationOptions = getResetPasswordMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    