/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * NTI Backend
 * API for NTI platform workflows, authentication, and administrative operations.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetMyStudentProfileResponseDto,
  UpdateAcademicInformationDto,
  UpdateProfessionalSkillsDto
} from '../index.schemas';

import { orvalMutator } from '../../api-client/openapi-runtime/runtime';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns profile completion status and profile data for the authenticated student.
 * @summary Get my student profile
 */
export const getMyStudentProfile = (
    
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<GetMyStudentProfileResponseDto>(
      {url: `/student-profile/me`, method: 'GET', signal
    },
      options);
    }
  



export const getGetMyStudentProfileQueryKey = () => {
    return [
    `/student-profile/me`
    ] as const;
    }

    
export const getGetMyStudentProfileQueryOptions = <TData = Awaited<ReturnType<typeof getMyStudentProfile>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyStudentProfile>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMyStudentProfileQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyStudentProfile>>> = ({ signal }) => getMyStudentProfile(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMyStudentProfile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMyStudentProfileQueryResult = NonNullable<Awaited<ReturnType<typeof getMyStudentProfile>>>
export type GetMyStudentProfileQueryError = void


export function useGetMyStudentProfile<TData = Awaited<ReturnType<typeof getMyStudentProfile>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyStudentProfile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyStudentProfile>>,
          TError,
          Awaited<ReturnType<typeof getMyStudentProfile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyStudentProfile<TData = Awaited<ReturnType<typeof getMyStudentProfile>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyStudentProfile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyStudentProfile>>,
          TError,
          Awaited<ReturnType<typeof getMyStudentProfile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyStudentProfile<TData = Awaited<ReturnType<typeof getMyStudentProfile>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyStudentProfile>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get my student profile
 */

export function useGetMyStudentProfile<TData = Awaited<ReturnType<typeof getMyStudentProfile>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyStudentProfile>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMyStudentProfileQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Creates or updates academic section of the student profile and validates selected hierarchy values.
 * @summary Update academic information
 */
export const updateMyStudentAcademicInformation = (
    updateAcademicInformationDto: UpdateAcademicInformationDto,
 options?: SecondParameter<typeof orvalMutator>,) => {
      
      
      return orvalMutator<GetMyStudentProfileResponseDto>(
      {url: `/student-profile/me/academic-information`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateAcademicInformationDto
    },
      options);
    }
  


export const getUpdateMyStudentAcademicInformationMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMyStudentAcademicInformation>>, TError,{data: UpdateAcademicInformationDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof updateMyStudentAcademicInformation>>, TError,{data: UpdateAcademicInformationDto}, TContext> => {

const mutationKey = ['updateMyStudentAcademicInformation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateMyStudentAcademicInformation>>, {data: UpdateAcademicInformationDto}> = (props) => {
          const {data} = props ?? {};

          return  updateMyStudentAcademicInformation(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateMyStudentAcademicInformationMutationResult = NonNullable<Awaited<ReturnType<typeof updateMyStudentAcademicInformation>>>
    export type UpdateMyStudentAcademicInformationMutationBody = UpdateAcademicInformationDto
    export type UpdateMyStudentAcademicInformationMutationError = void

    /**
 * @summary Update academic information
 */
export const useUpdateMyStudentAcademicInformation = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMyStudentAcademicInformation>>, TError,{data: UpdateAcademicInformationDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateMyStudentAcademicInformation>>,
        TError,
        {data: UpdateAcademicInformationDto},
        TContext
      > => {

      const mutationOptions = getUpdateMyStudentAcademicInformationMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Replaces professional profile section, including skills and optional projects.
 * @summary Update professional skills
 */
export const updateMyStudentProfessionalSkills = (
    updateProfessionalSkillsDto: UpdateProfessionalSkillsDto,
 options?: SecondParameter<typeof orvalMutator>,) => {
      
      
      return orvalMutator<GetMyStudentProfileResponseDto>(
      {url: `/student-profile/me/professional-skills`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateProfessionalSkillsDto
    },
      options);
    }
  


export const getUpdateMyStudentProfessionalSkillsMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMyStudentProfessionalSkills>>, TError,{data: UpdateProfessionalSkillsDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof updateMyStudentProfessionalSkills>>, TError,{data: UpdateProfessionalSkillsDto}, TContext> => {

const mutationKey = ['updateMyStudentProfessionalSkills'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateMyStudentProfessionalSkills>>, {data: UpdateProfessionalSkillsDto}> = (props) => {
          const {data} = props ?? {};

          return  updateMyStudentProfessionalSkills(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateMyStudentProfessionalSkillsMutationResult = NonNullable<Awaited<ReturnType<typeof updateMyStudentProfessionalSkills>>>
    export type UpdateMyStudentProfessionalSkillsMutationBody = UpdateProfessionalSkillsDto
    export type UpdateMyStudentProfessionalSkillsMutationError = void

    /**
 * @summary Update professional skills
 */
export const useUpdateMyStudentProfessionalSkills = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMyStudentProfessionalSkills>>, TError,{data: UpdateProfessionalSkillsDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateMyStudentProfessionalSkills>>,
        TError,
        {data: UpdateProfessionalSkillsDto},
        TContext
      > => {

      const mutationOptions = getUpdateMyStudentProfessionalSkillsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    