/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * NTI Backend
 * API for NTI platform workflows, authentication, and administrative operations.
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApplicationsReportResponseDto,
  ExportJobStatusDto,
  ProgramBReportResponseDto,
  ReportExportAcceptedDto,
  ReportsControllerDownloadExportJobParams,
  ReportsControllerExportAuditPdfParams,
  ReportsControllerExportReportParams,
  ReportsControllerGetApplicationsParams,
  ReportsControllerGetProgramBParams,
  ReportsDashboardDto
} from '../index.schemas';

import { orvalMutator } from '../../api-client/openapi-runtime/runtime';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns the minimal administrative reporting dashboard required by the NTI spec: grouped application counts, grouped organization counts, active Program B project count, currently open calls, and application decisions made within the last 30 days.
 * @summary Get reports dashboard KPIs
 */
export const reportsControllerGetDashboard = (
    
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<ReportsDashboardDto>(
      {url: `/reports/dashboard`, method: 'GET', signal
    },
      options);
    }
  



export const getReportsControllerGetDashboardQueryKey = () => {
    return [
    `/reports/dashboard`
    ] as const;
    }

    
export const getReportsControllerGetDashboardQueryOptions = <TData = Awaited<ReturnType<typeof reportsControllerGetDashboard>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerGetDashboard>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReportsControllerGetDashboardQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof reportsControllerGetDashboard>>> = ({ signal }) => reportsControllerGetDashboard(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof reportsControllerGetDashboard>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReportsControllerGetDashboardQueryResult = NonNullable<Awaited<ReturnType<typeof reportsControllerGetDashboard>>>
export type ReportsControllerGetDashboardQueryError = void


export function useReportsControllerGetDashboard<TData = Awaited<ReturnType<typeof reportsControllerGetDashboard>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerGetDashboard>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportsControllerGetDashboard>>,
          TError,
          Awaited<ReturnType<typeof reportsControllerGetDashboard>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReportsControllerGetDashboard<TData = Awaited<ReturnType<typeof reportsControllerGetDashboard>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerGetDashboard>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportsControllerGetDashboard>>,
          TError,
          Awaited<ReturnType<typeof reportsControllerGetDashboard>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReportsControllerGetDashboard<TData = Awaited<ReturnType<typeof reportsControllerGetDashboard>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerGetDashboard>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get reports dashboard KPIs
 */

export function useReportsControllerGetDashboard<TData = Awaited<ReturnType<typeof reportsControllerGetDashboard>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerGetDashboard>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReportsControllerGetDashboardQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Returns the Program A and Program B application reporting dataset as a paginated, filterable, and sortable admin-only list. Date filters apply to the application createdAt field.
 * @summary List applications report rows
 */
export const reportsControllerGetApplications = (
    params?: ReportsControllerGetApplicationsParams,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<ApplicationsReportResponseDto>(
      {url: `/reports/applications`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getReportsControllerGetApplicationsQueryKey = (params?: ReportsControllerGetApplicationsParams,) => {
    return [
    `/reports/applications`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getReportsControllerGetApplicationsQueryOptions = <TData = Awaited<ReturnType<typeof reportsControllerGetApplications>>, TError = void>(params?: ReportsControllerGetApplicationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerGetApplications>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReportsControllerGetApplicationsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof reportsControllerGetApplications>>> = ({ signal }) => reportsControllerGetApplications(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof reportsControllerGetApplications>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReportsControllerGetApplicationsQueryResult = NonNullable<Awaited<ReturnType<typeof reportsControllerGetApplications>>>
export type ReportsControllerGetApplicationsQueryError = void


export function useReportsControllerGetApplications<TData = Awaited<ReturnType<typeof reportsControllerGetApplications>>, TError = void>(
 params: undefined |  ReportsControllerGetApplicationsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerGetApplications>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportsControllerGetApplications>>,
          TError,
          Awaited<ReturnType<typeof reportsControllerGetApplications>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReportsControllerGetApplications<TData = Awaited<ReturnType<typeof reportsControllerGetApplications>>, TError = void>(
 params?: ReportsControllerGetApplicationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerGetApplications>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportsControllerGetApplications>>,
          TError,
          Awaited<ReturnType<typeof reportsControllerGetApplications>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReportsControllerGetApplications<TData = Awaited<ReturnType<typeof reportsControllerGetApplications>>, TError = void>(
 params?: ReportsControllerGetApplicationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerGetApplications>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List applications report rows
 */

export function useReportsControllerGetApplications<TData = Awaited<ReturnType<typeof reportsControllerGetApplications>>, TError = void>(
 params?: ReportsControllerGetApplicationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerGetApplications>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReportsControllerGetApplicationsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Returns the Program B team application reporting dataset as a paginated, filterable, and sortable admin-only list. Date filters apply to ProgramBTeamApplication.createdAt.
 * @summary List Program B report rows
 */
export const reportsControllerGetProgramB = (
    params?: ReportsControllerGetProgramBParams,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<ProgramBReportResponseDto>(
      {url: `/reports/program-b`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getReportsControllerGetProgramBQueryKey = (params?: ReportsControllerGetProgramBParams,) => {
    return [
    `/reports/program-b`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getReportsControllerGetProgramBQueryOptions = <TData = Awaited<ReturnType<typeof reportsControllerGetProgramB>>, TError = void>(params?: ReportsControllerGetProgramBParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerGetProgramB>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReportsControllerGetProgramBQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof reportsControllerGetProgramB>>> = ({ signal }) => reportsControllerGetProgramB(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof reportsControllerGetProgramB>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReportsControllerGetProgramBQueryResult = NonNullable<Awaited<ReturnType<typeof reportsControllerGetProgramB>>>
export type ReportsControllerGetProgramBQueryError = void


export function useReportsControllerGetProgramB<TData = Awaited<ReturnType<typeof reportsControllerGetProgramB>>, TError = void>(
 params: undefined |  ReportsControllerGetProgramBParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerGetProgramB>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportsControllerGetProgramB>>,
          TError,
          Awaited<ReturnType<typeof reportsControllerGetProgramB>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReportsControllerGetProgramB<TData = Awaited<ReturnType<typeof reportsControllerGetProgramB>>, TError = void>(
 params?: ReportsControllerGetProgramBParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerGetProgramB>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportsControllerGetProgramB>>,
          TError,
          Awaited<ReturnType<typeof reportsControllerGetProgramB>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReportsControllerGetProgramB<TData = Awaited<ReturnType<typeof reportsControllerGetProgramB>>, TError = void>(
 params?: ReportsControllerGetProgramBParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerGetProgramB>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Program B report rows
 */

export function useReportsControllerGetProgramB<TData = Awaited<ReturnType<typeof reportsControllerGetProgramB>>, TError = void>(
 params?: ReportsControllerGetProgramBParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerGetProgramB>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReportsControllerGetProgramBQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Exports either the applications dataset or the Program B dataset in CSV, XLSX, or PDF format.

Behavior:
- Small result sets are returned synchronously as a raw file response.
- Large result sets return HTTP 202 with exportJobId and continue through the async export path.

Query rules:
- dataset=applications uses the applications report filter set.
- dataset=program-b uses the Program B report filter set.
- status is dataset-specific and must match the selected dataset.
- sort and order follow the selected dataset rules but pagination params are intentionally not supported.
- programType is meaningful only for applications exports. For Program B exports, PROGRAM_A is rejected.
 * @summary Export report dataset
 */
export const reportsControllerExportReport = (
    params: ReportsControllerExportReportParams,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<Blob | ReportExportAcceptedDto>(
      {url: `/reports/export`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getReportsControllerExportReportQueryKey = (params?: ReportsControllerExportReportParams,) => {
    return [
    `/reports/export`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getReportsControllerExportReportQueryOptions = <TData = Awaited<ReturnType<typeof reportsControllerExportReport>>, TError = void>(params: ReportsControllerExportReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerExportReport>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReportsControllerExportReportQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof reportsControllerExportReport>>> = ({ signal }) => reportsControllerExportReport(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof reportsControllerExportReport>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReportsControllerExportReportQueryResult = NonNullable<Awaited<ReturnType<typeof reportsControllerExportReport>>>
export type ReportsControllerExportReportQueryError = void


export function useReportsControllerExportReport<TData = Awaited<ReturnType<typeof reportsControllerExportReport>>, TError = void>(
 params: ReportsControllerExportReportParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerExportReport>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportsControllerExportReport>>,
          TError,
          Awaited<ReturnType<typeof reportsControllerExportReport>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReportsControllerExportReport<TData = Awaited<ReturnType<typeof reportsControllerExportReport>>, TError = void>(
 params: ReportsControllerExportReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerExportReport>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportsControllerExportReport>>,
          TError,
          Awaited<ReturnType<typeof reportsControllerExportReport>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReportsControllerExportReport<TData = Awaited<ReturnType<typeof reportsControllerExportReport>>, TError = void>(
 params: ReportsControllerExportReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerExportReport>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Export report dataset
 */

export function useReportsControllerExportReport<TData = Awaited<ReturnType<typeof reportsControllerExportReport>>, TError = void>(
 params: ReportsControllerExportReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerExportReport>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReportsControllerExportReportQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Returns the status of an asynchronous export job. Completed jobs include a short-lived downloadUrl and downloadUrlExpiresAt.
 * @summary Get export job status
 */
export const reportsControllerGetExportJobStatus = (
    id: string,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<ExportJobStatusDto>(
      {url: `/reports/export-jobs/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getReportsControllerGetExportJobStatusQueryKey = (id?: string,) => {
    return [
    `/reports/export-jobs/${id}`
    ] as const;
    }

    
export const getReportsControllerGetExportJobStatusQueryOptions = <TData = Awaited<ReturnType<typeof reportsControllerGetExportJobStatus>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerGetExportJobStatus>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReportsControllerGetExportJobStatusQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof reportsControllerGetExportJobStatus>>> = ({ signal }) => reportsControllerGetExportJobStatus(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof reportsControllerGetExportJobStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReportsControllerGetExportJobStatusQueryResult = NonNullable<Awaited<ReturnType<typeof reportsControllerGetExportJobStatus>>>
export type ReportsControllerGetExportJobStatusQueryError = void


export function useReportsControllerGetExportJobStatus<TData = Awaited<ReturnType<typeof reportsControllerGetExportJobStatus>>, TError = void>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerGetExportJobStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportsControllerGetExportJobStatus>>,
          TError,
          Awaited<ReturnType<typeof reportsControllerGetExportJobStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReportsControllerGetExportJobStatus<TData = Awaited<ReturnType<typeof reportsControllerGetExportJobStatus>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerGetExportJobStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportsControllerGetExportJobStatus>>,
          TError,
          Awaited<ReturnType<typeof reportsControllerGetExportJobStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReportsControllerGetExportJobStatus<TData = Awaited<ReturnType<typeof reportsControllerGetExportJobStatus>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerGetExportJobStatus>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get export job status
 */

export function useReportsControllerGetExportJobStatus<TData = Awaited<ReturnType<typeof reportsControllerGetExportJobStatus>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerGetExportJobStatus>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReportsControllerGetExportJobStatusQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Redirects to a short-lived presigned storage URL for the file produced by a completed asynchronous export job.

Requirements:
- job must belong to the authenticated admin
- job must be COMPLETED
- token query parameter must match the current short-lived download token
 * @summary Download completed async export
 */
export const reportsControllerDownloadExportJob = (
    id: string,
    params: ReportsControllerDownloadExportJobParams,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<unknown>(
      {url: `/reports/export-jobs/${id}/download`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getReportsControllerDownloadExportJobQueryKey = (id?: string,
    params?: ReportsControllerDownloadExportJobParams,) => {
    return [
    `/reports/export-jobs/${id}/download`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getReportsControllerDownloadExportJobQueryOptions = <TData = Awaited<ReturnType<typeof reportsControllerDownloadExportJob>>, TError = void>(id: string,
    params: ReportsControllerDownloadExportJobParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerDownloadExportJob>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReportsControllerDownloadExportJobQueryKey(id,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof reportsControllerDownloadExportJob>>> = ({ signal }) => reportsControllerDownloadExportJob(id,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof reportsControllerDownloadExportJob>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReportsControllerDownloadExportJobQueryResult = NonNullable<Awaited<ReturnType<typeof reportsControllerDownloadExportJob>>>
export type ReportsControllerDownloadExportJobQueryError = void


export function useReportsControllerDownloadExportJob<TData = Awaited<ReturnType<typeof reportsControllerDownloadExportJob>>, TError = void>(
 id: string,
    params: ReportsControllerDownloadExportJobParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerDownloadExportJob>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportsControllerDownloadExportJob>>,
          TError,
          Awaited<ReturnType<typeof reportsControllerDownloadExportJob>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReportsControllerDownloadExportJob<TData = Awaited<ReturnType<typeof reportsControllerDownloadExportJob>>, TError = void>(
 id: string,
    params: ReportsControllerDownloadExportJobParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerDownloadExportJob>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportsControllerDownloadExportJob>>,
          TError,
          Awaited<ReturnType<typeof reportsControllerDownloadExportJob>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReportsControllerDownloadExportJob<TData = Awaited<ReturnType<typeof reportsControllerDownloadExportJob>>, TError = void>(
 id: string,
    params: ReportsControllerDownloadExportJobParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerDownloadExportJob>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Download completed async export
 */

export function useReportsControllerDownloadExportJob<TData = Awaited<ReturnType<typeof reportsControllerDownloadExportJob>>, TError = void>(
 id: string,
    params: ReportsControllerDownloadExportJobParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerDownloadExportJob>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReportsControllerDownloadExportJobQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Exports a human-readable PDF containing persisted report export audit events. This endpoint is intentionally PDF-only and does not expose generic audit history APIs.

Requirements:
- dateFrom is required
- dateTo is required
- dateTo must not be earlier than dateFrom
- requested date range must not exceed 31 days
 * @summary Export report export audit PDF
 */
export const reportsControllerExportAuditPdf = (
    params: ReportsControllerExportAuditPdfParams,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<Blob>(
      {url: `/reports/audit-export`, method: 'GET',
        params,
        responseType: 'blob', signal
    },
      options);
    }
  



export const getReportsControllerExportAuditPdfQueryKey = (params?: ReportsControllerExportAuditPdfParams,) => {
    return [
    `/reports/audit-export`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getReportsControllerExportAuditPdfQueryOptions = <TData = Awaited<ReturnType<typeof reportsControllerExportAuditPdf>>, TError = void>(params: ReportsControllerExportAuditPdfParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerExportAuditPdf>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReportsControllerExportAuditPdfQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof reportsControllerExportAuditPdf>>> = ({ signal }) => reportsControllerExportAuditPdf(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof reportsControllerExportAuditPdf>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReportsControllerExportAuditPdfQueryResult = NonNullable<Awaited<ReturnType<typeof reportsControllerExportAuditPdf>>>
export type ReportsControllerExportAuditPdfQueryError = void


export function useReportsControllerExportAuditPdf<TData = Awaited<ReturnType<typeof reportsControllerExportAuditPdf>>, TError = void>(
 params: ReportsControllerExportAuditPdfParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerExportAuditPdf>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportsControllerExportAuditPdf>>,
          TError,
          Awaited<ReturnType<typeof reportsControllerExportAuditPdf>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReportsControllerExportAuditPdf<TData = Awaited<ReturnType<typeof reportsControllerExportAuditPdf>>, TError = void>(
 params: ReportsControllerExportAuditPdfParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerExportAuditPdf>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportsControllerExportAuditPdf>>,
          TError,
          Awaited<ReturnType<typeof reportsControllerExportAuditPdf>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReportsControllerExportAuditPdf<TData = Awaited<ReturnType<typeof reportsControllerExportAuditPdf>>, TError = void>(
 params: ReportsControllerExportAuditPdfParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerExportAuditPdf>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Export report export audit PDF
 */

export function useReportsControllerExportAuditPdf<TData = Awaited<ReturnType<typeof reportsControllerExportAuditPdf>>, TError = void>(
 params: ReportsControllerExportAuditPdfParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerExportAuditPdf>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReportsControllerExportAuditPdfQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




