/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * NTI Backend
 * API for NTI platform workflows, authentication, and administrative operations.
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CompanyBacklogSummaryDto,
  CompanyProjectSummaryDto,
  ProgramBCompanyOverviewControllerGetBacklogSummaryParams,
  ProgramBCompanyOverviewControllerGetProjectSummaryParams,
  ProgramBCompanyOverviewDto
} from '../index.schemas';

import { orvalMutator } from '../../api-client/openapi-runtime/runtime';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns the organization-scoped Program B company overview for the authenticated company user, including top-level backlog, candidate, project, and pending-action counts.
 * @summary Get Program B company overview
 */
export const programBCompanyOverviewControllerGetOverview = (
    
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<ProgramBCompanyOverviewDto>(
      {url: `/program-b/company/overview`, method: 'GET', signal
    },
      options);
    }
  



export const getProgramBCompanyOverviewControllerGetOverviewQueryKey = () => {
    return [
    `/program-b/company/overview`
    ] as const;
    }

    
export const getProgramBCompanyOverviewControllerGetOverviewQueryOptions = <TData = Awaited<ReturnType<typeof programBCompanyOverviewControllerGetOverview>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBCompanyOverviewControllerGetOverview>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProgramBCompanyOverviewControllerGetOverviewQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof programBCompanyOverviewControllerGetOverview>>> = ({ signal }) => programBCompanyOverviewControllerGetOverview(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof programBCompanyOverviewControllerGetOverview>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProgramBCompanyOverviewControllerGetOverviewQueryResult = NonNullable<Awaited<ReturnType<typeof programBCompanyOverviewControllerGetOverview>>>
export type ProgramBCompanyOverviewControllerGetOverviewQueryError = void


export function useProgramBCompanyOverviewControllerGetOverview<TData = Awaited<ReturnType<typeof programBCompanyOverviewControllerGetOverview>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBCompanyOverviewControllerGetOverview>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof programBCompanyOverviewControllerGetOverview>>,
          TError,
          Awaited<ReturnType<typeof programBCompanyOverviewControllerGetOverview>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProgramBCompanyOverviewControllerGetOverview<TData = Awaited<ReturnType<typeof programBCompanyOverviewControllerGetOverview>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBCompanyOverviewControllerGetOverview>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof programBCompanyOverviewControllerGetOverview>>,
          TError,
          Awaited<ReturnType<typeof programBCompanyOverviewControllerGetOverview>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProgramBCompanyOverviewControllerGetOverview<TData = Awaited<ReturnType<typeof programBCompanyOverviewControllerGetOverview>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBCompanyOverviewControllerGetOverview>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Program B company overview
 */

export function useProgramBCompanyOverviewControllerGetOverview<TData = Awaited<ReturnType<typeof programBCompanyOverviewControllerGetOverview>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBCompanyOverviewControllerGetOverview>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProgramBCompanyOverviewControllerGetOverviewQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Returns a lightweight organization-scoped Program B backlog preview for the Program B company overview.
 * @summary Get Program B company backlog summary
 */
export const programBCompanyOverviewControllerGetBacklogSummary = (
    params?: ProgramBCompanyOverviewControllerGetBacklogSummaryParams,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<CompanyBacklogSummaryDto>(
      {url: `/program-b/company/backlog-summary`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getProgramBCompanyOverviewControllerGetBacklogSummaryQueryKey = (params?: ProgramBCompanyOverviewControllerGetBacklogSummaryParams,) => {
    return [
    `/program-b/company/backlog-summary`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getProgramBCompanyOverviewControllerGetBacklogSummaryQueryOptions = <TData = Awaited<ReturnType<typeof programBCompanyOverviewControllerGetBacklogSummary>>, TError = void>(params?: ProgramBCompanyOverviewControllerGetBacklogSummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBCompanyOverviewControllerGetBacklogSummary>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProgramBCompanyOverviewControllerGetBacklogSummaryQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof programBCompanyOverviewControllerGetBacklogSummary>>> = ({ signal }) => programBCompanyOverviewControllerGetBacklogSummary(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof programBCompanyOverviewControllerGetBacklogSummary>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProgramBCompanyOverviewControllerGetBacklogSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof programBCompanyOverviewControllerGetBacklogSummary>>>
export type ProgramBCompanyOverviewControllerGetBacklogSummaryQueryError = void


export function useProgramBCompanyOverviewControllerGetBacklogSummary<TData = Awaited<ReturnType<typeof programBCompanyOverviewControllerGetBacklogSummary>>, TError = void>(
 params: undefined |  ProgramBCompanyOverviewControllerGetBacklogSummaryParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBCompanyOverviewControllerGetBacklogSummary>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof programBCompanyOverviewControllerGetBacklogSummary>>,
          TError,
          Awaited<ReturnType<typeof programBCompanyOverviewControllerGetBacklogSummary>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProgramBCompanyOverviewControllerGetBacklogSummary<TData = Awaited<ReturnType<typeof programBCompanyOverviewControllerGetBacklogSummary>>, TError = void>(
 params?: ProgramBCompanyOverviewControllerGetBacklogSummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBCompanyOverviewControllerGetBacklogSummary>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof programBCompanyOverviewControllerGetBacklogSummary>>,
          TError,
          Awaited<ReturnType<typeof programBCompanyOverviewControllerGetBacklogSummary>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProgramBCompanyOverviewControllerGetBacklogSummary<TData = Awaited<ReturnType<typeof programBCompanyOverviewControllerGetBacklogSummary>>, TError = void>(
 params?: ProgramBCompanyOverviewControllerGetBacklogSummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBCompanyOverviewControllerGetBacklogSummary>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Program B company backlog summary
 */

export function useProgramBCompanyOverviewControllerGetBacklogSummary<TData = Awaited<ReturnType<typeof programBCompanyOverviewControllerGetBacklogSummary>>, TError = void>(
 params?: ProgramBCompanyOverviewControllerGetBacklogSummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBCompanyOverviewControllerGetBacklogSummary>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProgramBCompanyOverviewControllerGetBacklogSummaryQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Returns a lightweight organization-scoped Program B project preview for the Program B company overview.
 * @summary Get Program B company project summary
 */
export const programBCompanyOverviewControllerGetProjectSummary = (
    params?: ProgramBCompanyOverviewControllerGetProjectSummaryParams,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<CompanyProjectSummaryDto>(
      {url: `/program-b/company/project-summary`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getProgramBCompanyOverviewControllerGetProjectSummaryQueryKey = (params?: ProgramBCompanyOverviewControllerGetProjectSummaryParams,) => {
    return [
    `/program-b/company/project-summary`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getProgramBCompanyOverviewControllerGetProjectSummaryQueryOptions = <TData = Awaited<ReturnType<typeof programBCompanyOverviewControllerGetProjectSummary>>, TError = void>(params?: ProgramBCompanyOverviewControllerGetProjectSummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBCompanyOverviewControllerGetProjectSummary>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProgramBCompanyOverviewControllerGetProjectSummaryQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof programBCompanyOverviewControllerGetProjectSummary>>> = ({ signal }) => programBCompanyOverviewControllerGetProjectSummary(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof programBCompanyOverviewControllerGetProjectSummary>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProgramBCompanyOverviewControllerGetProjectSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof programBCompanyOverviewControllerGetProjectSummary>>>
export type ProgramBCompanyOverviewControllerGetProjectSummaryQueryError = void


export function useProgramBCompanyOverviewControllerGetProjectSummary<TData = Awaited<ReturnType<typeof programBCompanyOverviewControllerGetProjectSummary>>, TError = void>(
 params: undefined |  ProgramBCompanyOverviewControllerGetProjectSummaryParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBCompanyOverviewControllerGetProjectSummary>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof programBCompanyOverviewControllerGetProjectSummary>>,
          TError,
          Awaited<ReturnType<typeof programBCompanyOverviewControllerGetProjectSummary>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProgramBCompanyOverviewControllerGetProjectSummary<TData = Awaited<ReturnType<typeof programBCompanyOverviewControllerGetProjectSummary>>, TError = void>(
 params?: ProgramBCompanyOverviewControllerGetProjectSummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBCompanyOverviewControllerGetProjectSummary>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof programBCompanyOverviewControllerGetProjectSummary>>,
          TError,
          Awaited<ReturnType<typeof programBCompanyOverviewControllerGetProjectSummary>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProgramBCompanyOverviewControllerGetProjectSummary<TData = Awaited<ReturnType<typeof programBCompanyOverviewControllerGetProjectSummary>>, TError = void>(
 params?: ProgramBCompanyOverviewControllerGetProjectSummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBCompanyOverviewControllerGetProjectSummary>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Program B company project summary
 */

export function useProgramBCompanyOverviewControllerGetProjectSummary<TData = Awaited<ReturnType<typeof programBCompanyOverviewControllerGetProjectSummary>>, TError = void>(
 params?: ProgramBCompanyOverviewControllerGetProjectSummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBCompanyOverviewControllerGetProjectSummary>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProgramBCompanyOverviewControllerGetProjectSummaryQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




