/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * NTI Backend
 * API for NTI platform workflows, authentication, and administrative operations.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AdminFacultyDto,
  AdminListFacultiesParams,
  AdminListSpecializationsParams,
  AdminListUniversitiesParams,
  AdminSpecializationDto,
  AdminUniversityDto,
  CreateFacultyDto,
  CreateSpecializationDto,
  CreateUniversityDto,
  UpdateFacultyDto,
  UpdateSpecializationDto,
  UpdateUniversityDto
} from '../index.schemas';

import { orvalMutator } from '../../api-client/openapi-runtime/runtime';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns universities for administrators. Use includeInactive=true to include inactive records.
 * @summary List universities (admin)
 */
export const adminListUniversities = (
    params?: AdminListUniversitiesParams,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<AdminUniversityDto[]>(
      {url: `/admin/academic-structure/universities`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getAdminListUniversitiesQueryKey = (params?: AdminListUniversitiesParams,) => {
    return [
    `/admin/academic-structure/universities`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getAdminListUniversitiesQueryOptions = <TData = Awaited<ReturnType<typeof adminListUniversities>>, TError = void>(params?: AdminListUniversitiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListUniversities>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminListUniversitiesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminListUniversities>>> = ({ signal }) => adminListUniversities(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminListUniversities>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminListUniversitiesQueryResult = NonNullable<Awaited<ReturnType<typeof adminListUniversities>>>
export type AdminListUniversitiesQueryError = void


export function useAdminListUniversities<TData = Awaited<ReturnType<typeof adminListUniversities>>, TError = void>(
 params: undefined |  AdminListUniversitiesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListUniversities>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListUniversities>>,
          TError,
          Awaited<ReturnType<typeof adminListUniversities>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListUniversities<TData = Awaited<ReturnType<typeof adminListUniversities>>, TError = void>(
 params?: AdminListUniversitiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListUniversities>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListUniversities>>,
          TError,
          Awaited<ReturnType<typeof adminListUniversities>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListUniversities<TData = Awaited<ReturnType<typeof adminListUniversities>>, TError = void>(
 params?: AdminListUniversitiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListUniversities>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List universities (admin)
 */

export function useAdminListUniversities<TData = Awaited<ReturnType<typeof adminListUniversities>>, TError = void>(
 params?: AdminListUniversitiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListUniversities>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminListUniversitiesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Creates a university record.
 * @summary Create university (admin)
 */
export const adminCreateUniversity = (
    createUniversityDto: CreateUniversityDto,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<AdminUniversityDto>(
      {url: `/admin/academic-structure/universities`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createUniversityDto, signal
    },
      options);
    }
  


export const getAdminCreateUniversityMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateUniversity>>, TError,{data: CreateUniversityDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof adminCreateUniversity>>, TError,{data: CreateUniversityDto}, TContext> => {

const mutationKey = ['adminCreateUniversity'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminCreateUniversity>>, {data: CreateUniversityDto}> = (props) => {
          const {data} = props ?? {};

          return  adminCreateUniversity(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AdminCreateUniversityMutationResult = NonNullable<Awaited<ReturnType<typeof adminCreateUniversity>>>
    export type AdminCreateUniversityMutationBody = CreateUniversityDto
    export type AdminCreateUniversityMutationError = void

    /**
 * @summary Create university (admin)
 */
export const useAdminCreateUniversity = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateUniversity>>, TError,{data: CreateUniversityDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminCreateUniversity>>,
        TError,
        {data: CreateUniversityDto},
        TContext
      > => {

      const mutationOptions = getAdminCreateUniversityMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Returns faculties under a university for administrators. Use includeInactive=true to include inactive records.
 * @summary List faculties (admin)
 */
export const adminListFaculties = (
    universityId: string,
    params?: AdminListFacultiesParams,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<AdminFacultyDto[]>(
      {url: `/admin/academic-structure/universities/${universityId}/faculties`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getAdminListFacultiesQueryKey = (universityId?: string,
    params?: AdminListFacultiesParams,) => {
    return [
    `/admin/academic-structure/universities/${universityId}/faculties`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getAdminListFacultiesQueryOptions = <TData = Awaited<ReturnType<typeof adminListFaculties>>, TError = void>(universityId: string,
    params?: AdminListFacultiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListFaculties>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminListFacultiesQueryKey(universityId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminListFaculties>>> = ({ signal }) => adminListFaculties(universityId,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(universityId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminListFaculties>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminListFacultiesQueryResult = NonNullable<Awaited<ReturnType<typeof adminListFaculties>>>
export type AdminListFacultiesQueryError = void


export function useAdminListFaculties<TData = Awaited<ReturnType<typeof adminListFaculties>>, TError = void>(
 universityId: string,
    params: undefined |  AdminListFacultiesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListFaculties>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListFaculties>>,
          TError,
          Awaited<ReturnType<typeof adminListFaculties>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListFaculties<TData = Awaited<ReturnType<typeof adminListFaculties>>, TError = void>(
 universityId: string,
    params?: AdminListFacultiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListFaculties>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListFaculties>>,
          TError,
          Awaited<ReturnType<typeof adminListFaculties>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListFaculties<TData = Awaited<ReturnType<typeof adminListFaculties>>, TError = void>(
 universityId: string,
    params?: AdminListFacultiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListFaculties>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List faculties (admin)
 */

export function useAdminListFaculties<TData = Awaited<ReturnType<typeof adminListFaculties>>, TError = void>(
 universityId: string,
    params?: AdminListFacultiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListFaculties>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminListFacultiesQueryOptions(universityId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Returns specializations under a faculty for administrators. Use includeInactive=true to include inactive records.
 * @summary List specializations (admin)
 */
export const adminListSpecializations = (
    facultyId: string,
    params?: AdminListSpecializationsParams,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<AdminSpecializationDto[]>(
      {url: `/admin/academic-structure/faculties/${facultyId}/specializations`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getAdminListSpecializationsQueryKey = (facultyId?: string,
    params?: AdminListSpecializationsParams,) => {
    return [
    `/admin/academic-structure/faculties/${facultyId}/specializations`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getAdminListSpecializationsQueryOptions = <TData = Awaited<ReturnType<typeof adminListSpecializations>>, TError = void>(facultyId: string,
    params?: AdminListSpecializationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListSpecializations>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminListSpecializationsQueryKey(facultyId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminListSpecializations>>> = ({ signal }) => adminListSpecializations(facultyId,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(facultyId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminListSpecializations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminListSpecializationsQueryResult = NonNullable<Awaited<ReturnType<typeof adminListSpecializations>>>
export type AdminListSpecializationsQueryError = void


export function useAdminListSpecializations<TData = Awaited<ReturnType<typeof adminListSpecializations>>, TError = void>(
 facultyId: string,
    params: undefined |  AdminListSpecializationsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListSpecializations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListSpecializations>>,
          TError,
          Awaited<ReturnType<typeof adminListSpecializations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListSpecializations<TData = Awaited<ReturnType<typeof adminListSpecializations>>, TError = void>(
 facultyId: string,
    params?: AdminListSpecializationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListSpecializations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListSpecializations>>,
          TError,
          Awaited<ReturnType<typeof adminListSpecializations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListSpecializations<TData = Awaited<ReturnType<typeof adminListSpecializations>>, TError = void>(
 facultyId: string,
    params?: AdminListSpecializationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListSpecializations>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List specializations (admin)
 */

export function useAdminListSpecializations<TData = Awaited<ReturnType<typeof adminListSpecializations>>, TError = void>(
 facultyId: string,
    params?: AdminListSpecializationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListSpecializations>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminListSpecializationsQueryOptions(facultyId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Updates selected university fields.
 * @summary Update university (admin)
 */
export const adminUpdateUniversity = (
    universityId: string,
    updateUniversityDto: UpdateUniversityDto,
 options?: SecondParameter<typeof orvalMutator>,) => {
      
      
      return orvalMutator<AdminUniversityDto>(
      {url: `/admin/academic-structure/universities/${universityId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateUniversityDto
    },
      options);
    }
  


export const getAdminUpdateUniversityMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateUniversity>>, TError,{universityId: string;data: UpdateUniversityDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof adminUpdateUniversity>>, TError,{universityId: string;data: UpdateUniversityDto}, TContext> => {

const mutationKey = ['adminUpdateUniversity'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminUpdateUniversity>>, {universityId: string;data: UpdateUniversityDto}> = (props) => {
          const {universityId,data} = props ?? {};

          return  adminUpdateUniversity(universityId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AdminUpdateUniversityMutationResult = NonNullable<Awaited<ReturnType<typeof adminUpdateUniversity>>>
    export type AdminUpdateUniversityMutationBody = UpdateUniversityDto
    export type AdminUpdateUniversityMutationError = void

    /**
 * @summary Update university (admin)
 */
export const useAdminUpdateUniversity = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateUniversity>>, TError,{universityId: string;data: UpdateUniversityDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminUpdateUniversity>>,
        TError,
        {universityId: string;data: UpdateUniversityDto},
        TContext
      > => {

      const mutationOptions = getAdminUpdateUniversityMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Deletes a university record.
 * @summary Delete university (admin)
 */
export const adminAcademicStructureControllerDeleteUniversity = (
    universityId: string,
 options?: SecondParameter<typeof orvalMutator>,) => {
      
      
      return orvalMutator<void>(
      {url: `/admin/academic-structure/universities/${universityId}`, method: 'DELETE'
    },
      options);
    }
  


export const getAdminAcademicStructureControllerDeleteUniversityMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminAcademicStructureControllerDeleteUniversity>>, TError,{universityId: string}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof adminAcademicStructureControllerDeleteUniversity>>, TError,{universityId: string}, TContext> => {

const mutationKey = ['adminAcademicStructureControllerDeleteUniversity'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminAcademicStructureControllerDeleteUniversity>>, {universityId: string}> = (props) => {
          const {universityId} = props ?? {};

          return  adminAcademicStructureControllerDeleteUniversity(universityId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AdminAcademicStructureControllerDeleteUniversityMutationResult = NonNullable<Awaited<ReturnType<typeof adminAcademicStructureControllerDeleteUniversity>>>
    
    export type AdminAcademicStructureControllerDeleteUniversityMutationError = void

    /**
 * @summary Delete university (admin)
 */
export const useAdminAcademicStructureControllerDeleteUniversity = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminAcademicStructureControllerDeleteUniversity>>, TError,{universityId: string}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminAcademicStructureControllerDeleteUniversity>>,
        TError,
        {universityId: string},
        TContext
      > => {

      const mutationOptions = getAdminAcademicStructureControllerDeleteUniversityMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Creates a faculty record under a university.
 * @summary Create faculty (admin)
 */
export const adminCreateFaculty = (
    createFacultyDto: CreateFacultyDto,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<AdminFacultyDto>(
      {url: `/admin/academic-structure/faculties`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createFacultyDto, signal
    },
      options);
    }
  


export const getAdminCreateFacultyMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateFaculty>>, TError,{data: CreateFacultyDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof adminCreateFaculty>>, TError,{data: CreateFacultyDto}, TContext> => {

const mutationKey = ['adminCreateFaculty'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminCreateFaculty>>, {data: CreateFacultyDto}> = (props) => {
          const {data} = props ?? {};

          return  adminCreateFaculty(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AdminCreateFacultyMutationResult = NonNullable<Awaited<ReturnType<typeof adminCreateFaculty>>>
    export type AdminCreateFacultyMutationBody = CreateFacultyDto
    export type AdminCreateFacultyMutationError = void

    /**
 * @summary Create faculty (admin)
 */
export const useAdminCreateFaculty = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateFaculty>>, TError,{data: CreateFacultyDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminCreateFaculty>>,
        TError,
        {data: CreateFacultyDto},
        TContext
      > => {

      const mutationOptions = getAdminCreateFacultyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Updates selected faculty fields.
 * @summary Update faculty (admin)
 */
export const adminUpdateFaculty = (
    facultyId: string,
    updateFacultyDto: UpdateFacultyDto,
 options?: SecondParameter<typeof orvalMutator>,) => {
      
      
      return orvalMutator<AdminFacultyDto>(
      {url: `/admin/academic-structure/faculties/${facultyId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateFacultyDto
    },
      options);
    }
  


export const getAdminUpdateFacultyMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateFaculty>>, TError,{facultyId: string;data: UpdateFacultyDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof adminUpdateFaculty>>, TError,{facultyId: string;data: UpdateFacultyDto}, TContext> => {

const mutationKey = ['adminUpdateFaculty'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminUpdateFaculty>>, {facultyId: string;data: UpdateFacultyDto}> = (props) => {
          const {facultyId,data} = props ?? {};

          return  adminUpdateFaculty(facultyId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AdminUpdateFacultyMutationResult = NonNullable<Awaited<ReturnType<typeof adminUpdateFaculty>>>
    export type AdminUpdateFacultyMutationBody = UpdateFacultyDto
    export type AdminUpdateFacultyMutationError = void

    /**
 * @summary Update faculty (admin)
 */
export const useAdminUpdateFaculty = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateFaculty>>, TError,{facultyId: string;data: UpdateFacultyDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminUpdateFaculty>>,
        TError,
        {facultyId: string;data: UpdateFacultyDto},
        TContext
      > => {

      const mutationOptions = getAdminUpdateFacultyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Deletes a faculty record.
 * @summary Delete faculty (admin)
 */
export const adminAcademicStructureControllerDeleteFaculty = (
    facultyId: string,
 options?: SecondParameter<typeof orvalMutator>,) => {
      
      
      return orvalMutator<void>(
      {url: `/admin/academic-structure/faculties/${facultyId}`, method: 'DELETE'
    },
      options);
    }
  


export const getAdminAcademicStructureControllerDeleteFacultyMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminAcademicStructureControllerDeleteFaculty>>, TError,{facultyId: string}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof adminAcademicStructureControllerDeleteFaculty>>, TError,{facultyId: string}, TContext> => {

const mutationKey = ['adminAcademicStructureControllerDeleteFaculty'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminAcademicStructureControllerDeleteFaculty>>, {facultyId: string}> = (props) => {
          const {facultyId} = props ?? {};

          return  adminAcademicStructureControllerDeleteFaculty(facultyId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AdminAcademicStructureControllerDeleteFacultyMutationResult = NonNullable<Awaited<ReturnType<typeof adminAcademicStructureControllerDeleteFaculty>>>
    
    export type AdminAcademicStructureControllerDeleteFacultyMutationError = void

    /**
 * @summary Delete faculty (admin)
 */
export const useAdminAcademicStructureControllerDeleteFaculty = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminAcademicStructureControllerDeleteFaculty>>, TError,{facultyId: string}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminAcademicStructureControllerDeleteFaculty>>,
        TError,
        {facultyId: string},
        TContext
      > => {

      const mutationOptions = getAdminAcademicStructureControllerDeleteFacultyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Creates a specialization record under a faculty.
 * @summary Create specialization (admin)
 */
export const adminCreateSpecialization = (
    createSpecializationDto: CreateSpecializationDto,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<AdminSpecializationDto>(
      {url: `/admin/academic-structure/specializations`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createSpecializationDto, signal
    },
      options);
    }
  


export const getAdminCreateSpecializationMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateSpecialization>>, TError,{data: CreateSpecializationDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof adminCreateSpecialization>>, TError,{data: CreateSpecializationDto}, TContext> => {

const mutationKey = ['adminCreateSpecialization'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminCreateSpecialization>>, {data: CreateSpecializationDto}> = (props) => {
          const {data} = props ?? {};

          return  adminCreateSpecialization(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AdminCreateSpecializationMutationResult = NonNullable<Awaited<ReturnType<typeof adminCreateSpecialization>>>
    export type AdminCreateSpecializationMutationBody = CreateSpecializationDto
    export type AdminCreateSpecializationMutationError = void

    /**
 * @summary Create specialization (admin)
 */
export const useAdminCreateSpecialization = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateSpecialization>>, TError,{data: CreateSpecializationDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminCreateSpecialization>>,
        TError,
        {data: CreateSpecializationDto},
        TContext
      > => {

      const mutationOptions = getAdminCreateSpecializationMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Updates selected specialization fields.
 * @summary Update specialization (admin)
 */
export const adminUpdateSpecialization = (
    specializationId: string,
    updateSpecializationDto: UpdateSpecializationDto,
 options?: SecondParameter<typeof orvalMutator>,) => {
      
      
      return orvalMutator<AdminSpecializationDto>(
      {url: `/admin/academic-structure/specializations/${specializationId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateSpecializationDto
    },
      options);
    }
  


export const getAdminUpdateSpecializationMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateSpecialization>>, TError,{specializationId: string;data: UpdateSpecializationDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof adminUpdateSpecialization>>, TError,{specializationId: string;data: UpdateSpecializationDto}, TContext> => {

const mutationKey = ['adminUpdateSpecialization'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminUpdateSpecialization>>, {specializationId: string;data: UpdateSpecializationDto}> = (props) => {
          const {specializationId,data} = props ?? {};

          return  adminUpdateSpecialization(specializationId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AdminUpdateSpecializationMutationResult = NonNullable<Awaited<ReturnType<typeof adminUpdateSpecialization>>>
    export type AdminUpdateSpecializationMutationBody = UpdateSpecializationDto
    export type AdminUpdateSpecializationMutationError = void

    /**
 * @summary Update specialization (admin)
 */
export const useAdminUpdateSpecialization = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateSpecialization>>, TError,{specializationId: string;data: UpdateSpecializationDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminUpdateSpecialization>>,
        TError,
        {specializationId: string;data: UpdateSpecializationDto},
        TContext
      > => {

      const mutationOptions = getAdminUpdateSpecializationMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Deletes a specialization record.
 * @summary Delete specialization (admin)
 */
export const adminAcademicStructureControllerDeleteSpecialization = (
    specializationId: string,
 options?: SecondParameter<typeof orvalMutator>,) => {
      
      
      return orvalMutator<void>(
      {url: `/admin/academic-structure/specializations/${specializationId}`, method: 'DELETE'
    },
      options);
    }
  


export const getAdminAcademicStructureControllerDeleteSpecializationMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminAcademicStructureControllerDeleteSpecialization>>, TError,{specializationId: string}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof adminAcademicStructureControllerDeleteSpecialization>>, TError,{specializationId: string}, TContext> => {

const mutationKey = ['adminAcademicStructureControllerDeleteSpecialization'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminAcademicStructureControllerDeleteSpecialization>>, {specializationId: string}> = (props) => {
          const {specializationId} = props ?? {};

          return  adminAcademicStructureControllerDeleteSpecialization(specializationId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AdminAcademicStructureControllerDeleteSpecializationMutationResult = NonNullable<Awaited<ReturnType<typeof adminAcademicStructureControllerDeleteSpecialization>>>
    
    export type AdminAcademicStructureControllerDeleteSpecializationMutationError = void

    /**
 * @summary Delete specialization (admin)
 */
export const useAdminAcademicStructureControllerDeleteSpecialization = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminAcademicStructureControllerDeleteSpecialization>>, TError,{specializationId: string}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminAcademicStructureControllerDeleteSpecialization>>,
        TError,
        {specializationId: string},
        TContext
      > => {

      const mutationOptions = getAdminAcademicStructureControllerDeleteSpecializationMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    