/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * NTI Backend
 * API for NTI platform workflows, authentication, and administrative operations.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApplicationDetailDto,
  ApplicationDocumentDto,
  ApplicationEvaluationDto,
  ApplicationSectionDto,
  ApplicationSectionHistoryDto,
  ApplicationSectionKey,
  ApplicationsControllerListActivePublicCallsParams,
  ApplicationsControllerListPublicCallsParams,
  AssignMentorDto,
  AttachApplicationDocumentDto,
  CreateApplicationDecisionDto,
  CreateApplicationDto,
  CreateApplicationEvaluationDto,
  CreateMentorshipNoteDto,
  CreateNeedsInfoItemDto,
  CreateNeedsInfoReplyDto,
  DocumentCompletenessDto,
  EligibilitySignalsResponseDto,
  MentorAssignmentDto,
  NeedsInfoItemDto,
  NeedsInfoReplyDto,
  NeedsInfoThreadDto,
  ProgramAMentorshipNoteDto,
  PublicCallDto,
  PublicCallsResponseDto,
  ResubmitApplicationDto,
  SetActiveSectionVersionDto,
  UpsertApplicationSectionDto
} from '../index.schemas';

import { orvalMutator } from '../../api-client/openapi-runtime/runtime';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns a paginated list of publicly visible calls using only public-safe fields.
 * @summary List public calls
 */
export const applicationsControllerListPublicCalls = (
    params?: ApplicationsControllerListPublicCallsParams,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<PublicCallsResponseDto>(
      {url: `/applications/calls`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getApplicationsControllerListPublicCallsQueryKey = (params?: ApplicationsControllerListPublicCallsParams,) => {
    return [
    `/applications/calls`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getApplicationsControllerListPublicCallsQueryOptions = <TData = Awaited<ReturnType<typeof applicationsControllerListPublicCalls>>, TError = void>(params?: ApplicationsControllerListPublicCallsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerListPublicCalls>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApplicationsControllerListPublicCallsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof applicationsControllerListPublicCalls>>> = ({ signal }) => applicationsControllerListPublicCalls(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerListPublicCalls>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApplicationsControllerListPublicCallsQueryResult = NonNullable<Awaited<ReturnType<typeof applicationsControllerListPublicCalls>>>
export type ApplicationsControllerListPublicCallsQueryError = void


export function useApplicationsControllerListPublicCalls<TData = Awaited<ReturnType<typeof applicationsControllerListPublicCalls>>, TError = void>(
 params: undefined |  ApplicationsControllerListPublicCallsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerListPublicCalls>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof applicationsControllerListPublicCalls>>,
          TError,
          Awaited<ReturnType<typeof applicationsControllerListPublicCalls>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApplicationsControllerListPublicCalls<TData = Awaited<ReturnType<typeof applicationsControllerListPublicCalls>>, TError = void>(
 params?: ApplicationsControllerListPublicCallsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerListPublicCalls>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof applicationsControllerListPublicCalls>>,
          TError,
          Awaited<ReturnType<typeof applicationsControllerListPublicCalls>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApplicationsControllerListPublicCalls<TData = Awaited<ReturnType<typeof applicationsControllerListPublicCalls>>, TError = void>(
 params?: ApplicationsControllerListPublicCallsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerListPublicCalls>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List public calls
 */

export function useApplicationsControllerListPublicCalls<TData = Awaited<ReturnType<typeof applicationsControllerListPublicCalls>>, TError = void>(
 params?: ApplicationsControllerListPublicCallsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerListPublicCalls>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApplicationsControllerListPublicCallsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Returns a paginated list of public calls that are OPEN and currently within their visibility date window.
 * @summary List active public calls
 */
export const applicationsControllerListActivePublicCalls = (
    params?: ApplicationsControllerListActivePublicCallsParams,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<PublicCallsResponseDto>(
      {url: `/applications/calls/active`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getApplicationsControllerListActivePublicCallsQueryKey = (params?: ApplicationsControllerListActivePublicCallsParams,) => {
    return [
    `/applications/calls/active`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getApplicationsControllerListActivePublicCallsQueryOptions = <TData = Awaited<ReturnType<typeof applicationsControllerListActivePublicCalls>>, TError = void>(params?: ApplicationsControllerListActivePublicCallsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerListActivePublicCalls>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApplicationsControllerListActivePublicCallsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof applicationsControllerListActivePublicCalls>>> = ({ signal }) => applicationsControllerListActivePublicCalls(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerListActivePublicCalls>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApplicationsControllerListActivePublicCallsQueryResult = NonNullable<Awaited<ReturnType<typeof applicationsControllerListActivePublicCalls>>>
export type ApplicationsControllerListActivePublicCallsQueryError = void


export function useApplicationsControllerListActivePublicCalls<TData = Awaited<ReturnType<typeof applicationsControllerListActivePublicCalls>>, TError = void>(
 params: undefined |  ApplicationsControllerListActivePublicCallsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerListActivePublicCalls>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof applicationsControllerListActivePublicCalls>>,
          TError,
          Awaited<ReturnType<typeof applicationsControllerListActivePublicCalls>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApplicationsControllerListActivePublicCalls<TData = Awaited<ReturnType<typeof applicationsControllerListActivePublicCalls>>, TError = void>(
 params?: ApplicationsControllerListActivePublicCallsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerListActivePublicCalls>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof applicationsControllerListActivePublicCalls>>,
          TError,
          Awaited<ReturnType<typeof applicationsControllerListActivePublicCalls>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApplicationsControllerListActivePublicCalls<TData = Awaited<ReturnType<typeof applicationsControllerListActivePublicCalls>>, TError = void>(
 params?: ApplicationsControllerListActivePublicCallsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerListActivePublicCalls>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List active public calls
 */

export function useApplicationsControllerListActivePublicCalls<TData = Awaited<ReturnType<typeof applicationsControllerListActivePublicCalls>>, TError = void>(
 params?: ApplicationsControllerListActivePublicCallsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerListActivePublicCalls>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApplicationsControllerListActivePublicCallsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Returns public call details when the call exists and is allowed to be exposed publicly.
 * @summary Get public call by id
 */
export const applicationsControllerFindPublicCallById = (
    id: string,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<PublicCallDto>(
      {url: `/applications/calls/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getApplicationsControllerFindPublicCallByIdQueryKey = (id?: string,) => {
    return [
    `/applications/calls/${id}`
    ] as const;
    }

    
export const getApplicationsControllerFindPublicCallByIdQueryOptions = <TData = Awaited<ReturnType<typeof applicationsControllerFindPublicCallById>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerFindPublicCallById>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApplicationsControllerFindPublicCallByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof applicationsControllerFindPublicCallById>>> = ({ signal }) => applicationsControllerFindPublicCallById(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerFindPublicCallById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApplicationsControllerFindPublicCallByIdQueryResult = NonNullable<Awaited<ReturnType<typeof applicationsControllerFindPublicCallById>>>
export type ApplicationsControllerFindPublicCallByIdQueryError = void


export function useApplicationsControllerFindPublicCallById<TData = Awaited<ReturnType<typeof applicationsControllerFindPublicCallById>>, TError = void>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerFindPublicCallById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof applicationsControllerFindPublicCallById>>,
          TError,
          Awaited<ReturnType<typeof applicationsControllerFindPublicCallById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApplicationsControllerFindPublicCallById<TData = Awaited<ReturnType<typeof applicationsControllerFindPublicCallById>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerFindPublicCallById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof applicationsControllerFindPublicCallById>>,
          TError,
          Awaited<ReturnType<typeof applicationsControllerFindPublicCallById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApplicationsControllerFindPublicCallById<TData = Awaited<ReturnType<typeof applicationsControllerFindPublicCallById>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerFindPublicCallById>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get public call by id
 */

export function useApplicationsControllerFindPublicCallById<TData = Awaited<ReturnType<typeof applicationsControllerFindPublicCallById>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerFindPublicCallById>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApplicationsControllerFindPublicCallByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Creates a draft application for a team in a target call when the call is open and within its application window, the team is not archived, and the requester is the team lead.
 * @summary Create draft application
 */
export const applicationsControllerCreateDraft = (
    createApplicationDto: CreateApplicationDto,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<ApplicationDetailDto>(
      {url: `/applications`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createApplicationDto, signal
    },
      options);
    }
  


export const getApplicationsControllerCreateDraftMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof applicationsControllerCreateDraft>>, TError,{data: CreateApplicationDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof applicationsControllerCreateDraft>>, TError,{data: CreateApplicationDto}, TContext> => {

const mutationKey = ['applicationsControllerCreateDraft'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof applicationsControllerCreateDraft>>, {data: CreateApplicationDto}> = (props) => {
          const {data} = props ?? {};

          return  applicationsControllerCreateDraft(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ApplicationsControllerCreateDraftMutationResult = NonNullable<Awaited<ReturnType<typeof applicationsControllerCreateDraft>>>
    export type ApplicationsControllerCreateDraftMutationBody = CreateApplicationDto
    export type ApplicationsControllerCreateDraftMutationError = void

    /**
 * @summary Create draft application
 */
export const useApplicationsControllerCreateDraft = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof applicationsControllerCreateDraft>>, TError,{data: CreateApplicationDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof applicationsControllerCreateDraft>>,
        TError,
        {data: CreateApplicationDto},
        TContext
      > => {

      const mutationOptions = getApplicationsControllerCreateDraftMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Returns application details by identifier.
 * @summary Get application by id
 */
export const applicationsControllerFindById = (
    id: string,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<ApplicationDetailDto>(
      {url: `/applications/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getApplicationsControllerFindByIdQueryKey = (id?: string,) => {
    return [
    `/applications/${id}`
    ] as const;
    }

    
export const getApplicationsControllerFindByIdQueryOptions = <TData = Awaited<ReturnType<typeof applicationsControllerFindById>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerFindById>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApplicationsControllerFindByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof applicationsControllerFindById>>> = ({ signal }) => applicationsControllerFindById(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerFindById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApplicationsControllerFindByIdQueryResult = NonNullable<Awaited<ReturnType<typeof applicationsControllerFindById>>>
export type ApplicationsControllerFindByIdQueryError = void


export function useApplicationsControllerFindById<TData = Awaited<ReturnType<typeof applicationsControllerFindById>>, TError = void>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerFindById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof applicationsControllerFindById>>,
          TError,
          Awaited<ReturnType<typeof applicationsControllerFindById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApplicationsControllerFindById<TData = Awaited<ReturnType<typeof applicationsControllerFindById>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerFindById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof applicationsControllerFindById>>,
          TError,
          Awaited<ReturnType<typeof applicationsControllerFindById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApplicationsControllerFindById<TData = Awaited<ReturnType<typeof applicationsControllerFindById>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerFindById>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get application by id
 */

export function useApplicationsControllerFindById<TData = Awaited<ReturnType<typeof applicationsControllerFindById>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerFindById>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApplicationsControllerFindByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Attaches an already uploaded file to an application document slot. Team lead only. CV attachments require memberUserId and count per team member.
 * @summary Attach application document
 */
export const applicationsControllerAttachDocument = (
    id: string,
    attachApplicationDocumentDto: AttachApplicationDocumentDto,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<ApplicationDocumentDto>(
      {url: `/applications/${id}/documents`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: attachApplicationDocumentDto, signal
    },
      options);
    }
  


export const getApplicationsControllerAttachDocumentMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof applicationsControllerAttachDocument>>, TError,{id: string;data: AttachApplicationDocumentDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof applicationsControllerAttachDocument>>, TError,{id: string;data: AttachApplicationDocumentDto}, TContext> => {

const mutationKey = ['applicationsControllerAttachDocument'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof applicationsControllerAttachDocument>>, {id: string;data: AttachApplicationDocumentDto}> = (props) => {
          const {id,data} = props ?? {};

          return  applicationsControllerAttachDocument(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ApplicationsControllerAttachDocumentMutationResult = NonNullable<Awaited<ReturnType<typeof applicationsControllerAttachDocument>>>
    export type ApplicationsControllerAttachDocumentMutationBody = AttachApplicationDocumentDto
    export type ApplicationsControllerAttachDocumentMutationError = void

    /**
 * @summary Attach application document
 */
export const useApplicationsControllerAttachDocument = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof applicationsControllerAttachDocument>>, TError,{id: string;data: AttachApplicationDocumentDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof applicationsControllerAttachDocument>>,
        TError,
        {id: string;data: AttachApplicationDocumentDto},
        TContext
      > => {

      const mutationOptions = getApplicationsControllerAttachDocumentMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Returns the exact required document slots that are satisfied or missing for the application.
 * @summary Get application document completeness
 */
export const applicationsControllerGetDocumentCompleteness = (
    id: string,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<DocumentCompletenessDto>(
      {url: `/applications/${id}/document-completeness`, method: 'GET', signal
    },
      options);
    }
  



export const getApplicationsControllerGetDocumentCompletenessQueryKey = (id?: string,) => {
    return [
    `/applications/${id}/document-completeness`
    ] as const;
    }

    
export const getApplicationsControllerGetDocumentCompletenessQueryOptions = <TData = Awaited<ReturnType<typeof applicationsControllerGetDocumentCompleteness>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerGetDocumentCompleteness>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApplicationsControllerGetDocumentCompletenessQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof applicationsControllerGetDocumentCompleteness>>> = ({ signal }) => applicationsControllerGetDocumentCompleteness(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerGetDocumentCompleteness>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApplicationsControllerGetDocumentCompletenessQueryResult = NonNullable<Awaited<ReturnType<typeof applicationsControllerGetDocumentCompleteness>>>
export type ApplicationsControllerGetDocumentCompletenessQueryError = void


export function useApplicationsControllerGetDocumentCompleteness<TData = Awaited<ReturnType<typeof applicationsControllerGetDocumentCompleteness>>, TError = void>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerGetDocumentCompleteness>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof applicationsControllerGetDocumentCompleteness>>,
          TError,
          Awaited<ReturnType<typeof applicationsControllerGetDocumentCompleteness>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApplicationsControllerGetDocumentCompleteness<TData = Awaited<ReturnType<typeof applicationsControllerGetDocumentCompleteness>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerGetDocumentCompleteness>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof applicationsControllerGetDocumentCompleteness>>,
          TError,
          Awaited<ReturnType<typeof applicationsControllerGetDocumentCompleteness>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApplicationsControllerGetDocumentCompleteness<TData = Awaited<ReturnType<typeof applicationsControllerGetDocumentCompleteness>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerGetDocumentCompleteness>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get application document completeness
 */

export function useApplicationsControllerGetDocumentCompleteness<TData = Awaited<ReturnType<typeof applicationsControllerGetDocumentCompleteness>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerGetDocumentCompleteness>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApplicationsControllerGetDocumentCompletenessQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Recomputes and returns eligibility signals for an application. Accessible to reviewer-side users and application team members.
 * @summary Get application eligibility signals
 */
export const applicationsControllerGetEligibilitySignals = (
    id: string,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<EligibilitySignalsResponseDto>(
      {url: `/applications/${id}/eligibility-signals`, method: 'GET', signal
    },
      options);
    }
  



export const getApplicationsControllerGetEligibilitySignalsQueryKey = (id?: string,) => {
    return [
    `/applications/${id}/eligibility-signals`
    ] as const;
    }

    
export const getApplicationsControllerGetEligibilitySignalsQueryOptions = <TData = Awaited<ReturnType<typeof applicationsControllerGetEligibilitySignals>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerGetEligibilitySignals>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApplicationsControllerGetEligibilitySignalsQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof applicationsControllerGetEligibilitySignals>>> = ({ signal }) => applicationsControllerGetEligibilitySignals(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerGetEligibilitySignals>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApplicationsControllerGetEligibilitySignalsQueryResult = NonNullable<Awaited<ReturnType<typeof applicationsControllerGetEligibilitySignals>>>
export type ApplicationsControllerGetEligibilitySignalsQueryError = void


export function useApplicationsControllerGetEligibilitySignals<TData = Awaited<ReturnType<typeof applicationsControllerGetEligibilitySignals>>, TError = void>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerGetEligibilitySignals>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof applicationsControllerGetEligibilitySignals>>,
          TError,
          Awaited<ReturnType<typeof applicationsControllerGetEligibilitySignals>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApplicationsControllerGetEligibilitySignals<TData = Awaited<ReturnType<typeof applicationsControllerGetEligibilitySignals>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerGetEligibilitySignals>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof applicationsControllerGetEligibilitySignals>>,
          TError,
          Awaited<ReturnType<typeof applicationsControllerGetEligibilitySignals>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApplicationsControllerGetEligibilitySignals<TData = Awaited<ReturnType<typeof applicationsControllerGetEligibilitySignals>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerGetEligibilitySignals>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get application eligibility signals
 */

export function useApplicationsControllerGetEligibilitySignals<TData = Awaited<ReturnType<typeof applicationsControllerGetEligibilitySignals>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerGetEligibilitySignals>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApplicationsControllerGetEligibilitySignalsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Reviewer-side users can submit one criterion-based evaluation for an application in FORMALLY_VERIFIED or EVALUATING status. The MVP requires TECHNICAL_QUALITY, BUSINESS_VALUE, and TEAM_CAPABILITY scores.
 * @summary Create application evaluation
 */
export const applicationsControllerCreateEvaluation = (
    id: string,
    createApplicationEvaluationDto: CreateApplicationEvaluationDto,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<ApplicationEvaluationDto>(
      {url: `/applications/${id}/evaluations`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createApplicationEvaluationDto, signal
    },
      options);
    }
  


export const getApplicationsControllerCreateEvaluationMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof applicationsControllerCreateEvaluation>>, TError,{id: string;data: CreateApplicationEvaluationDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof applicationsControllerCreateEvaluation>>, TError,{id: string;data: CreateApplicationEvaluationDto}, TContext> => {

const mutationKey = ['applicationsControllerCreateEvaluation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof applicationsControllerCreateEvaluation>>, {id: string;data: CreateApplicationEvaluationDto}> = (props) => {
          const {id,data} = props ?? {};

          return  applicationsControllerCreateEvaluation(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ApplicationsControllerCreateEvaluationMutationResult = NonNullable<Awaited<ReturnType<typeof applicationsControllerCreateEvaluation>>>
    export type ApplicationsControllerCreateEvaluationMutationBody = CreateApplicationEvaluationDto
    export type ApplicationsControllerCreateEvaluationMutationError = void

    /**
 * @summary Create application evaluation
 */
export const useApplicationsControllerCreateEvaluation = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof applicationsControllerCreateEvaluation>>, TError,{id: string;data: CreateApplicationEvaluationDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof applicationsControllerCreateEvaluation>>,
        TError,
        {id: string;data: CreateApplicationEvaluationDto},
        TContext
      > => {

      const mutationOptions = getApplicationsControllerCreateEvaluationMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Returns criterion-based evaluations for an application. Reviewer-side users only.
 * @summary List application evaluations
 */
export const applicationsControllerListEvaluations = (
    id: string,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<ApplicationEvaluationDto[]>(
      {url: `/applications/${id}/evaluations`, method: 'GET', signal
    },
      options);
    }
  



export const getApplicationsControllerListEvaluationsQueryKey = (id?: string,) => {
    return [
    `/applications/${id}/evaluations`
    ] as const;
    }

    
export const getApplicationsControllerListEvaluationsQueryOptions = <TData = Awaited<ReturnType<typeof applicationsControllerListEvaluations>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerListEvaluations>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApplicationsControllerListEvaluationsQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof applicationsControllerListEvaluations>>> = ({ signal }) => applicationsControllerListEvaluations(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerListEvaluations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApplicationsControllerListEvaluationsQueryResult = NonNullable<Awaited<ReturnType<typeof applicationsControllerListEvaluations>>>
export type ApplicationsControllerListEvaluationsQueryError = void


export function useApplicationsControllerListEvaluations<TData = Awaited<ReturnType<typeof applicationsControllerListEvaluations>>, TError = void>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerListEvaluations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof applicationsControllerListEvaluations>>,
          TError,
          Awaited<ReturnType<typeof applicationsControllerListEvaluations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApplicationsControllerListEvaluations<TData = Awaited<ReturnType<typeof applicationsControllerListEvaluations>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerListEvaluations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof applicationsControllerListEvaluations>>,
          TError,
          Awaited<ReturnType<typeof applicationsControllerListEvaluations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApplicationsControllerListEvaluations<TData = Awaited<ReturnType<typeof applicationsControllerListEvaluations>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerListEvaluations>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List application evaluations
 */

export function useApplicationsControllerListEvaluations<TData = Awaited<ReturnType<typeof applicationsControllerListEvaluations>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerListEvaluations>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApplicationsControllerListEvaluationsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Reviewer-side users can approve or reject an application after at least one complete evaluation exists. The decision stores status, decidedAt, decisionById, decisionRationale, and creates an application status event.
 * @summary Create final application decision
 */
export const applicationsControllerCreateDecision = (
    id: string,
    createApplicationDecisionDto: CreateApplicationDecisionDto,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<ApplicationDetailDto>(
      {url: `/applications/${id}/decision`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createApplicationDecisionDto, signal
    },
      options);
    }
  


export const getApplicationsControllerCreateDecisionMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof applicationsControllerCreateDecision>>, TError,{id: string;data: CreateApplicationDecisionDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof applicationsControllerCreateDecision>>, TError,{id: string;data: CreateApplicationDecisionDto}, TContext> => {

const mutationKey = ['applicationsControllerCreateDecision'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof applicationsControllerCreateDecision>>, {id: string;data: CreateApplicationDecisionDto}> = (props) => {
          const {id,data} = props ?? {};

          return  applicationsControllerCreateDecision(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ApplicationsControllerCreateDecisionMutationResult = NonNullable<Awaited<ReturnType<typeof applicationsControllerCreateDecision>>>
    export type ApplicationsControllerCreateDecisionMutationBody = CreateApplicationDecisionDto
    export type ApplicationsControllerCreateDecisionMutationError = void

    /**
 * @summary Create final application decision
 */
export const useApplicationsControllerCreateDecision = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof applicationsControllerCreateDecision>>, TError,{id: string;data: CreateApplicationDecisionDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof applicationsControllerCreateDecision>>,
        TError,
        {id: string;data: CreateApplicationDecisionDto},
        TContext
      > => {

      const mutationOptions = getApplicationsControllerCreateDecisionMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Submits a draft application. Program A submissions require a complete document pack. Successful submission locks the team.
 * @summary Submit application
 */
export const applicationsControllerSubmit = (
    id: string,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<ApplicationDetailDto>(
      {url: `/applications/${id}/submit`, method: 'POST', signal
    },
      options);
    }
  


export const getApplicationsControllerSubmitMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof applicationsControllerSubmit>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof applicationsControllerSubmit>>, TError,{id: string}, TContext> => {

const mutationKey = ['applicationsControllerSubmit'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof applicationsControllerSubmit>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  applicationsControllerSubmit(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ApplicationsControllerSubmitMutationResult = NonNullable<Awaited<ReturnType<typeof applicationsControllerSubmit>>>
    
    export type ApplicationsControllerSubmitMutationError = void

    /**
 * @summary Submit application
 */
export const useApplicationsControllerSubmit = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof applicationsControllerSubmit>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof applicationsControllerSubmit>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getApplicationsControllerSubmitMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Reviewer-side users can request additional information for submitted applications. The application moves to NEEDS_INFO.
 * @summary Request additional information for application
 */
export const applicationsControllerCreateNeedsInfoItem = (
    id: string,
    createNeedsInfoItemDto: CreateNeedsInfoItemDto,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<NeedsInfoItemDto>(
      {url: `/applications/${id}/needs-info-items`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createNeedsInfoItemDto, signal
    },
      options);
    }
  


export const getApplicationsControllerCreateNeedsInfoItemMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof applicationsControllerCreateNeedsInfoItem>>, TError,{id: string;data: CreateNeedsInfoItemDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof applicationsControllerCreateNeedsInfoItem>>, TError,{id: string;data: CreateNeedsInfoItemDto}, TContext> => {

const mutationKey = ['applicationsControllerCreateNeedsInfoItem'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof applicationsControllerCreateNeedsInfoItem>>, {id: string;data: CreateNeedsInfoItemDto}> = (props) => {
          const {id,data} = props ?? {};

          return  applicationsControllerCreateNeedsInfoItem(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ApplicationsControllerCreateNeedsInfoItemMutationResult = NonNullable<Awaited<ReturnType<typeof applicationsControllerCreateNeedsInfoItem>>>
    export type ApplicationsControllerCreateNeedsInfoItemMutationBody = CreateNeedsInfoItemDto
    export type ApplicationsControllerCreateNeedsInfoItemMutationError = void

    /**
 * @summary Request additional information for application
 */
export const useApplicationsControllerCreateNeedsInfoItem = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof applicationsControllerCreateNeedsInfoItem>>, TError,{id: string;data: CreateNeedsInfoItemDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof applicationsControllerCreateNeedsInfoItem>>,
        TError,
        {id: string;data: CreateNeedsInfoItemDto},
        TContext
      > => {

      const mutationOptions = getApplicationsControllerCreateNeedsInfoItemMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Team lead can reply to an open needs-info item while the application is in NEEDS_INFO status.
 * @summary Reply to needs-info item
 */
export const applicationsControllerReplyToNeedsInfoItem = (
    id: string,
    itemId: string,
    createNeedsInfoReplyDto: CreateNeedsInfoReplyDto,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<NeedsInfoReplyDto>(
      {url: `/applications/${id}/needs-info-items/${itemId}/replies`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createNeedsInfoReplyDto, signal
    },
      options);
    }
  


export const getApplicationsControllerReplyToNeedsInfoItemMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof applicationsControllerReplyToNeedsInfoItem>>, TError,{id: string;itemId: string;data: CreateNeedsInfoReplyDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof applicationsControllerReplyToNeedsInfoItem>>, TError,{id: string;itemId: string;data: CreateNeedsInfoReplyDto}, TContext> => {

const mutationKey = ['applicationsControllerReplyToNeedsInfoItem'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof applicationsControllerReplyToNeedsInfoItem>>, {id: string;itemId: string;data: CreateNeedsInfoReplyDto}> = (props) => {
          const {id,itemId,data} = props ?? {};

          return  applicationsControllerReplyToNeedsInfoItem(id,itemId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ApplicationsControllerReplyToNeedsInfoItemMutationResult = NonNullable<Awaited<ReturnType<typeof applicationsControllerReplyToNeedsInfoItem>>>
    export type ApplicationsControllerReplyToNeedsInfoItemMutationBody = CreateNeedsInfoReplyDto
    export type ApplicationsControllerReplyToNeedsInfoItemMutationError = void

    /**
 * @summary Reply to needs-info item
 */
export const useApplicationsControllerReplyToNeedsInfoItem = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof applicationsControllerReplyToNeedsInfoItem>>, TError,{id: string;itemId: string;data: CreateNeedsInfoReplyDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof applicationsControllerReplyToNeedsInfoItem>>,
        TError,
        {id: string;itemId: string;data: CreateNeedsInfoReplyDto},
        TContext
      > => {

      const mutationOptions = getApplicationsControllerReplyToNeedsInfoItemMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Team lead can resubmit an application from NEEDS_INFO to EVALUATING after all needs-info items have been answered.
 * @summary Resubmit application after needs-info replies
 */
export const applicationsControllerResubmit = (
    id: string,
    resubmitApplicationDto: ResubmitApplicationDto,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<ApplicationDetailDto>(
      {url: `/applications/${id}/resubmit`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: resubmitApplicationDto, signal
    },
      options);
    }
  


export const getApplicationsControllerResubmitMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof applicationsControllerResubmit>>, TError,{id: string;data: ResubmitApplicationDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof applicationsControllerResubmit>>, TError,{id: string;data: ResubmitApplicationDto}, TContext> => {

const mutationKey = ['applicationsControllerResubmit'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof applicationsControllerResubmit>>, {id: string;data: ResubmitApplicationDto}> = (props) => {
          const {id,data} = props ?? {};

          return  applicationsControllerResubmit(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ApplicationsControllerResubmitMutationResult = NonNullable<Awaited<ReturnType<typeof applicationsControllerResubmit>>>
    export type ApplicationsControllerResubmitMutationBody = ResubmitApplicationDto
    export type ApplicationsControllerResubmitMutationError = void

    /**
 * @summary Resubmit application after needs-info replies
 */
export const useApplicationsControllerResubmit = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof applicationsControllerResubmit>>, TError,{id: string;data: ResubmitApplicationDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof applicationsControllerResubmit>>,
        TError,
        {id: string;data: ResubmitApplicationDto},
        TContext
      > => {

      const mutationOptions = getApplicationsControllerResubmitMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Returns needs-info items, replies, and application status events for the application.
 * @summary Get needs-info thread
 */
export const applicationsControllerGetNeedsInfoThread = (
    id: string,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<NeedsInfoThreadDto>(
      {url: `/applications/${id}/needs-info-thread`, method: 'GET', signal
    },
      options);
    }
  



export const getApplicationsControllerGetNeedsInfoThreadQueryKey = (id?: string,) => {
    return [
    `/applications/${id}/needs-info-thread`
    ] as const;
    }

    
export const getApplicationsControllerGetNeedsInfoThreadQueryOptions = <TData = Awaited<ReturnType<typeof applicationsControllerGetNeedsInfoThread>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerGetNeedsInfoThread>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApplicationsControllerGetNeedsInfoThreadQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof applicationsControllerGetNeedsInfoThread>>> = ({ signal }) => applicationsControllerGetNeedsInfoThread(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerGetNeedsInfoThread>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApplicationsControllerGetNeedsInfoThreadQueryResult = NonNullable<Awaited<ReturnType<typeof applicationsControllerGetNeedsInfoThread>>>
export type ApplicationsControllerGetNeedsInfoThreadQueryError = void


export function useApplicationsControllerGetNeedsInfoThread<TData = Awaited<ReturnType<typeof applicationsControllerGetNeedsInfoThread>>, TError = void>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerGetNeedsInfoThread>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof applicationsControllerGetNeedsInfoThread>>,
          TError,
          Awaited<ReturnType<typeof applicationsControllerGetNeedsInfoThread>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApplicationsControllerGetNeedsInfoThread<TData = Awaited<ReturnType<typeof applicationsControllerGetNeedsInfoThread>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerGetNeedsInfoThread>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof applicationsControllerGetNeedsInfoThread>>,
          TError,
          Awaited<ReturnType<typeof applicationsControllerGetNeedsInfoThread>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApplicationsControllerGetNeedsInfoThread<TData = Awaited<ReturnType<typeof applicationsControllerGetNeedsInfoThread>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerGetNeedsInfoThread>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get needs-info thread
 */

export function useApplicationsControllerGetNeedsInfoThread<TData = Awaited<ReturnType<typeof applicationsControllerGetNeedsInfoThread>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerGetNeedsInfoThread>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApplicationsControllerGetNeedsInfoThreadQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Assigns or reassigns the current mentor for an approved-or-later Program A application. Admin and super-admin only.
 * @summary Assign mentor to Program A application
 */
export const applicationsControllerAssignMentor = (
    id: string,
    assignMentorDto: AssignMentorDto,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<MentorAssignmentDto>(
      {url: `/applications/${id}/assign-mentor`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: assignMentorDto, signal
    },
      options);
    }
  


export const getApplicationsControllerAssignMentorMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof applicationsControllerAssignMentor>>, TError,{id: string;data: AssignMentorDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof applicationsControllerAssignMentor>>, TError,{id: string;data: AssignMentorDto}, TContext> => {

const mutationKey = ['applicationsControllerAssignMentor'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof applicationsControllerAssignMentor>>, {id: string;data: AssignMentorDto}> = (props) => {
          const {id,data} = props ?? {};

          return  applicationsControllerAssignMentor(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ApplicationsControllerAssignMentorMutationResult = NonNullable<Awaited<ReturnType<typeof applicationsControllerAssignMentor>>>
    export type ApplicationsControllerAssignMentorMutationBody = AssignMentorDto
    export type ApplicationsControllerAssignMentorMutationError = void

    /**
 * @summary Assign mentor to Program A application
 */
export const useApplicationsControllerAssignMentor = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof applicationsControllerAssignMentor>>, TError,{id: string;data: AssignMentorDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof applicationsControllerAssignMentor>>,
        TError,
        {id: string;data: AssignMentorDto},
        TContext
      > => {

      const mutationOptions = getApplicationsControllerAssignMentorMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Creates an append-only mentorship note for a Program A application. Accessible to the assigned mentor, admin, and super-admin.
 * @summary Create Program A mentorship note
 */
export const applicationsControllerCreateMentorshipNote = (
    id: string,
    createMentorshipNoteDto: CreateMentorshipNoteDto,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<ProgramAMentorshipNoteDto>(
      {url: `/applications/${id}/mentorship-notes`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createMentorshipNoteDto, signal
    },
      options);
    }
  


export const getApplicationsControllerCreateMentorshipNoteMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof applicationsControllerCreateMentorshipNote>>, TError,{id: string;data: CreateMentorshipNoteDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof applicationsControllerCreateMentorshipNote>>, TError,{id: string;data: CreateMentorshipNoteDto}, TContext> => {

const mutationKey = ['applicationsControllerCreateMentorshipNote'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof applicationsControllerCreateMentorshipNote>>, {id: string;data: CreateMentorshipNoteDto}> = (props) => {
          const {id,data} = props ?? {};

          return  applicationsControllerCreateMentorshipNote(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ApplicationsControllerCreateMentorshipNoteMutationResult = NonNullable<Awaited<ReturnType<typeof applicationsControllerCreateMentorshipNote>>>
    export type ApplicationsControllerCreateMentorshipNoteMutationBody = CreateMentorshipNoteDto
    export type ApplicationsControllerCreateMentorshipNoteMutationError = void

    /**
 * @summary Create Program A mentorship note
 */
export const useApplicationsControllerCreateMentorshipNote = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof applicationsControllerCreateMentorshipNote>>, TError,{id: string;data: CreateMentorshipNoteDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof applicationsControllerCreateMentorshipNote>>,
        TError,
        {id: string;data: CreateMentorshipNoteDto},
        TContext
      > => {

      const mutationOptions = getApplicationsControllerCreateMentorshipNoteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Returns mentorship notes for a Program A application in deterministic ascending order.
 * @summary List Program A mentorship notes
 */
export const applicationsControllerListMentorshipNotes = (
    id: string,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<ProgramAMentorshipNoteDto[]>(
      {url: `/applications/${id}/mentorship-notes`, method: 'GET', signal
    },
      options);
    }
  



export const getApplicationsControllerListMentorshipNotesQueryKey = (id?: string,) => {
    return [
    `/applications/${id}/mentorship-notes`
    ] as const;
    }

    
export const getApplicationsControllerListMentorshipNotesQueryOptions = <TData = Awaited<ReturnType<typeof applicationsControllerListMentorshipNotes>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerListMentorshipNotes>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApplicationsControllerListMentorshipNotesQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof applicationsControllerListMentorshipNotes>>> = ({ signal }) => applicationsControllerListMentorshipNotes(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerListMentorshipNotes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApplicationsControllerListMentorshipNotesQueryResult = NonNullable<Awaited<ReturnType<typeof applicationsControllerListMentorshipNotes>>>
export type ApplicationsControllerListMentorshipNotesQueryError = void


export function useApplicationsControllerListMentorshipNotes<TData = Awaited<ReturnType<typeof applicationsControllerListMentorshipNotes>>, TError = void>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerListMentorshipNotes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof applicationsControllerListMentorshipNotes>>,
          TError,
          Awaited<ReturnType<typeof applicationsControllerListMentorshipNotes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApplicationsControllerListMentorshipNotes<TData = Awaited<ReturnType<typeof applicationsControllerListMentorshipNotes>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerListMentorshipNotes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof applicationsControllerListMentorshipNotes>>,
          TError,
          Awaited<ReturnType<typeof applicationsControllerListMentorshipNotes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApplicationsControllerListMentorshipNotes<TData = Awaited<ReturnType<typeof applicationsControllerListMentorshipNotes>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerListMentorshipNotes>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Program A mentorship notes
 */

export function useApplicationsControllerListMentorshipNotes<TData = Awaited<ReturnType<typeof applicationsControllerListMentorshipNotes>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerListMentorshipNotes>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApplicationsControllerListMentorshipNotesQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Returns all sections for an application with resolved active values.
 * @summary List application sections
 */
export const applicationsControllerListSections = (
    applicationId: string,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<ApplicationSectionDto[]>(
      {url: `/applications/${applicationId}/sections`, method: 'GET', signal
    },
      options);
    }
  



export const getApplicationsControllerListSectionsQueryKey = (applicationId?: string,) => {
    return [
    `/applications/${applicationId}/sections`
    ] as const;
    }

    
export const getApplicationsControllerListSectionsQueryOptions = <TData = Awaited<ReturnType<typeof applicationsControllerListSections>>, TError = void>(applicationId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerListSections>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApplicationsControllerListSectionsQueryKey(applicationId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof applicationsControllerListSections>>> = ({ signal }) => applicationsControllerListSections(applicationId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(applicationId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerListSections>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApplicationsControllerListSectionsQueryResult = NonNullable<Awaited<ReturnType<typeof applicationsControllerListSections>>>
export type ApplicationsControllerListSectionsQueryError = void


export function useApplicationsControllerListSections<TData = Awaited<ReturnType<typeof applicationsControllerListSections>>, TError = void>(
 applicationId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerListSections>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof applicationsControllerListSections>>,
          TError,
          Awaited<ReturnType<typeof applicationsControllerListSections>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApplicationsControllerListSections<TData = Awaited<ReturnType<typeof applicationsControllerListSections>>, TError = void>(
 applicationId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerListSections>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof applicationsControllerListSections>>,
          TError,
          Awaited<ReturnType<typeof applicationsControllerListSections>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApplicationsControllerListSections<TData = Awaited<ReturnType<typeof applicationsControllerListSections>>, TError = void>(
 applicationId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerListSections>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List application sections
 */

export function useApplicationsControllerListSections<TData = Awaited<ReturnType<typeof applicationsControllerListSections>>, TError = void>(
 applicationId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerListSections>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApplicationsControllerListSectionsQueryOptions(applicationId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Creates or updates one application section and stores its history snapshot.
 * @summary Upsert application section
 */
export const applicationsControllerUpsertSection = (
    applicationId: string,
    key: ApplicationSectionKey,
    upsertApplicationSectionDto: UpsertApplicationSectionDto,
 options?: SecondParameter<typeof orvalMutator>,) => {
      
      
      return orvalMutator<ApplicationSectionDto>(
      {url: `/applications/${applicationId}/sections/${key}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: upsertApplicationSectionDto
    },
      options);
    }
  


export const getApplicationsControllerUpsertSectionMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof applicationsControllerUpsertSection>>, TError,{applicationId: string;key: ApplicationSectionKey;data: UpsertApplicationSectionDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof applicationsControllerUpsertSection>>, TError,{applicationId: string;key: ApplicationSectionKey;data: UpsertApplicationSectionDto}, TContext> => {

const mutationKey = ['applicationsControllerUpsertSection'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof applicationsControllerUpsertSection>>, {applicationId: string;key: ApplicationSectionKey;data: UpsertApplicationSectionDto}> = (props) => {
          const {applicationId,key,data} = props ?? {};

          return  applicationsControllerUpsertSection(applicationId,key,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ApplicationsControllerUpsertSectionMutationResult = NonNullable<Awaited<ReturnType<typeof applicationsControllerUpsertSection>>>
    export type ApplicationsControllerUpsertSectionMutationBody = UpsertApplicationSectionDto
    export type ApplicationsControllerUpsertSectionMutationError = void

    /**
 * @summary Upsert application section
 */
export const useApplicationsControllerUpsertSection = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof applicationsControllerUpsertSection>>, TError,{applicationId: string;key: ApplicationSectionKey;data: UpsertApplicationSectionDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof applicationsControllerUpsertSection>>,
        TError,
        {applicationId: string;key: ApplicationSectionKey;data: UpsertApplicationSectionDto},
        TContext
      > => {

      const mutationOptions = getApplicationsControllerUpsertSectionMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Returns the history snapshots for a section. Admin only.
 * @summary Get section change history
 */
export const applicationsControllerGetSectionHistory = (
    applicationId: string,
    key: ApplicationSectionKey,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<ApplicationSectionHistoryDto[]>(
      {url: `/applications/${applicationId}/sections/${key}/history`, method: 'GET', signal
    },
      options);
    }
  



export const getApplicationsControllerGetSectionHistoryQueryKey = (applicationId?: string,
    key?: ApplicationSectionKey,) => {
    return [
    `/applications/${applicationId}/sections/${key}/history`
    ] as const;
    }

    
export const getApplicationsControllerGetSectionHistoryQueryOptions = <TData = Awaited<ReturnType<typeof applicationsControllerGetSectionHistory>>, TError = void>(applicationId: string,
    key: ApplicationSectionKey, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerGetSectionHistory>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApplicationsControllerGetSectionHistoryQueryKey(applicationId,key);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof applicationsControllerGetSectionHistory>>> = ({ signal }) => applicationsControllerGetSectionHistory(applicationId,key, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(applicationId && key), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerGetSectionHistory>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApplicationsControllerGetSectionHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof applicationsControllerGetSectionHistory>>>
export type ApplicationsControllerGetSectionHistoryQueryError = void


export function useApplicationsControllerGetSectionHistory<TData = Awaited<ReturnType<typeof applicationsControllerGetSectionHistory>>, TError = void>(
 applicationId: string,
    key: ApplicationSectionKey, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerGetSectionHistory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof applicationsControllerGetSectionHistory>>,
          TError,
          Awaited<ReturnType<typeof applicationsControllerGetSectionHistory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApplicationsControllerGetSectionHistory<TData = Awaited<ReturnType<typeof applicationsControllerGetSectionHistory>>, TError = void>(
 applicationId: string,
    key: ApplicationSectionKey, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerGetSectionHistory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof applicationsControllerGetSectionHistory>>,
          TError,
          Awaited<ReturnType<typeof applicationsControllerGetSectionHistory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApplicationsControllerGetSectionHistory<TData = Awaited<ReturnType<typeof applicationsControllerGetSectionHistory>>, TError = void>(
 applicationId: string,
    key: ApplicationSectionKey, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerGetSectionHistory>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get section change history
 */

export function useApplicationsControllerGetSectionHistory<TData = Awaited<ReturnType<typeof applicationsControllerGetSectionHistory>>, TError = void>(
 applicationId: string,
    key: ApplicationSectionKey, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof applicationsControllerGetSectionHistory>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApplicationsControllerGetSectionHistoryQueryOptions(applicationId,key,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Pins a historical version as the active payload for a section. Admin only.
 * @summary Set active section version
 */
export const applicationsControllerSetActiveVersion = (
    applicationId: string,
    key: ApplicationSectionKey,
    setActiveSectionVersionDto: SetActiveSectionVersionDto,
 options?: SecondParameter<typeof orvalMutator>,) => {
      
      
      return orvalMutator<ApplicationSectionDto>(
      {url: `/applications/${applicationId}/sections/${key}/active-version`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: setActiveSectionVersionDto
    },
      options);
    }
  


export const getApplicationsControllerSetActiveVersionMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof applicationsControllerSetActiveVersion>>, TError,{applicationId: string;key: ApplicationSectionKey;data: SetActiveSectionVersionDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof applicationsControllerSetActiveVersion>>, TError,{applicationId: string;key: ApplicationSectionKey;data: SetActiveSectionVersionDto}, TContext> => {

const mutationKey = ['applicationsControllerSetActiveVersion'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof applicationsControllerSetActiveVersion>>, {applicationId: string;key: ApplicationSectionKey;data: SetActiveSectionVersionDto}> = (props) => {
          const {applicationId,key,data} = props ?? {};

          return  applicationsControllerSetActiveVersion(applicationId,key,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ApplicationsControllerSetActiveVersionMutationResult = NonNullable<Awaited<ReturnType<typeof applicationsControllerSetActiveVersion>>>
    export type ApplicationsControllerSetActiveVersionMutationBody = SetActiveSectionVersionDto
    export type ApplicationsControllerSetActiveVersionMutationError = void

    /**
 * @summary Set active section version
 */
export const useApplicationsControllerSetActiveVersion = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof applicationsControllerSetActiveVersion>>, TError,{applicationId: string;key: ApplicationSectionKey;data: SetActiveSectionVersionDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof applicationsControllerSetActiveVersion>>,
        TError,
        {applicationId: string;key: ApplicationSectionKey;data: SetActiveSectionVersionDto},
        TContext
      > => {

      const mutationOptions = getApplicationsControllerSetActiveVersionMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    