/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * NTI Backend
 * API for NTI platform workflows, authentication, and administrative operations.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ConversationAttachmentDownloadDto,
  ConversationMessageDto,
  ConversationMessagePageDto,
  CreateConversationMessageDto,
  UpdateConversationMessageDto
} from '../index.schemas';

import { orvalMutator } from '../../api-client/openapi-runtime/runtime';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const conversationsControllerListProgramBMessages = (
    projectId: string,
    channel: string,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<ConversationMessagePageDto>(
      {url: `/program-b/projects/${projectId}/conversations/${channel}/messages`, method: 'GET', signal
    },
      options);
    }
  



export const getConversationsControllerListProgramBMessagesQueryKey = (projectId?: string,
    channel?: string,) => {
    return [
    `/program-b/projects/${projectId}/conversations/${channel}/messages`
    ] as const;
    }

    
export const getConversationsControllerListProgramBMessagesQueryOptions = <TData = Awaited<ReturnType<typeof conversationsControllerListProgramBMessages>>, TError = unknown>(projectId: string,
    channel: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof conversationsControllerListProgramBMessages>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getConversationsControllerListProgramBMessagesQueryKey(projectId,channel);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof conversationsControllerListProgramBMessages>>> = ({ signal }) => conversationsControllerListProgramBMessages(projectId,channel, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(projectId && channel), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof conversationsControllerListProgramBMessages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ConversationsControllerListProgramBMessagesQueryResult = NonNullable<Awaited<ReturnType<typeof conversationsControllerListProgramBMessages>>>
export type ConversationsControllerListProgramBMessagesQueryError = unknown


export function useConversationsControllerListProgramBMessages<TData = Awaited<ReturnType<typeof conversationsControllerListProgramBMessages>>, TError = unknown>(
 projectId: string,
    channel: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof conversationsControllerListProgramBMessages>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof conversationsControllerListProgramBMessages>>,
          TError,
          Awaited<ReturnType<typeof conversationsControllerListProgramBMessages>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useConversationsControllerListProgramBMessages<TData = Awaited<ReturnType<typeof conversationsControllerListProgramBMessages>>, TError = unknown>(
 projectId: string,
    channel: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof conversationsControllerListProgramBMessages>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof conversationsControllerListProgramBMessages>>,
          TError,
          Awaited<ReturnType<typeof conversationsControllerListProgramBMessages>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useConversationsControllerListProgramBMessages<TData = Awaited<ReturnType<typeof conversationsControllerListProgramBMessages>>, TError = unknown>(
 projectId: string,
    channel: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof conversationsControllerListProgramBMessages>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useConversationsControllerListProgramBMessages<TData = Awaited<ReturnType<typeof conversationsControllerListProgramBMessages>>, TError = unknown>(
 projectId: string,
    channel: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof conversationsControllerListProgramBMessages>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getConversationsControllerListProgramBMessagesQueryOptions(projectId,channel,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const conversationsControllerCreateProgramBMessage = (
    projectId: string,
    channel: string,
    createConversationMessageDto: CreateConversationMessageDto,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<ConversationMessageDto>(
      {url: `/program-b/projects/${projectId}/conversations/${channel}/messages`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createConversationMessageDto, signal
    },
      options);
    }
  


export const getConversationsControllerCreateProgramBMessageMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof conversationsControllerCreateProgramBMessage>>, TError,{projectId: string;channel: string;data: CreateConversationMessageDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof conversationsControllerCreateProgramBMessage>>, TError,{projectId: string;channel: string;data: CreateConversationMessageDto}, TContext> => {

const mutationKey = ['conversationsControllerCreateProgramBMessage'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof conversationsControllerCreateProgramBMessage>>, {projectId: string;channel: string;data: CreateConversationMessageDto}> = (props) => {
          const {projectId,channel,data} = props ?? {};

          return  conversationsControllerCreateProgramBMessage(projectId,channel,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ConversationsControllerCreateProgramBMessageMutationResult = NonNullable<Awaited<ReturnType<typeof conversationsControllerCreateProgramBMessage>>>
    export type ConversationsControllerCreateProgramBMessageMutationBody = CreateConversationMessageDto
    export type ConversationsControllerCreateProgramBMessageMutationError = unknown

    export const useConversationsControllerCreateProgramBMessage = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof conversationsControllerCreateProgramBMessage>>, TError,{projectId: string;channel: string;data: CreateConversationMessageDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof conversationsControllerCreateProgramBMessage>>,
        TError,
        {projectId: string;channel: string;data: CreateConversationMessageDto},
        TContext
      > => {

      const mutationOptions = getConversationsControllerCreateProgramBMessageMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const conversationsControllerListProgramAMessages = (
    applicationId: string,
    channel: string,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<ConversationMessagePageDto>(
      {url: `/program-a/applications/${applicationId}/conversations/${channel}/messages`, method: 'GET', signal
    },
      options);
    }
  



export const getConversationsControllerListProgramAMessagesQueryKey = (applicationId?: string,
    channel?: string,) => {
    return [
    `/program-a/applications/${applicationId}/conversations/${channel}/messages`
    ] as const;
    }

    
export const getConversationsControllerListProgramAMessagesQueryOptions = <TData = Awaited<ReturnType<typeof conversationsControllerListProgramAMessages>>, TError = unknown>(applicationId: string,
    channel: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof conversationsControllerListProgramAMessages>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getConversationsControllerListProgramAMessagesQueryKey(applicationId,channel);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof conversationsControllerListProgramAMessages>>> = ({ signal }) => conversationsControllerListProgramAMessages(applicationId,channel, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(applicationId && channel), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof conversationsControllerListProgramAMessages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ConversationsControllerListProgramAMessagesQueryResult = NonNullable<Awaited<ReturnType<typeof conversationsControllerListProgramAMessages>>>
export type ConversationsControllerListProgramAMessagesQueryError = unknown


export function useConversationsControllerListProgramAMessages<TData = Awaited<ReturnType<typeof conversationsControllerListProgramAMessages>>, TError = unknown>(
 applicationId: string,
    channel: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof conversationsControllerListProgramAMessages>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof conversationsControllerListProgramAMessages>>,
          TError,
          Awaited<ReturnType<typeof conversationsControllerListProgramAMessages>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useConversationsControllerListProgramAMessages<TData = Awaited<ReturnType<typeof conversationsControllerListProgramAMessages>>, TError = unknown>(
 applicationId: string,
    channel: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof conversationsControllerListProgramAMessages>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof conversationsControllerListProgramAMessages>>,
          TError,
          Awaited<ReturnType<typeof conversationsControllerListProgramAMessages>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useConversationsControllerListProgramAMessages<TData = Awaited<ReturnType<typeof conversationsControllerListProgramAMessages>>, TError = unknown>(
 applicationId: string,
    channel: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof conversationsControllerListProgramAMessages>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useConversationsControllerListProgramAMessages<TData = Awaited<ReturnType<typeof conversationsControllerListProgramAMessages>>, TError = unknown>(
 applicationId: string,
    channel: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof conversationsControllerListProgramAMessages>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getConversationsControllerListProgramAMessagesQueryOptions(applicationId,channel,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const conversationsControllerCreateProgramAMessage = (
    applicationId: string,
    channel: string,
    createConversationMessageDto: CreateConversationMessageDto,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<ConversationMessageDto>(
      {url: `/program-a/applications/${applicationId}/conversations/${channel}/messages`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createConversationMessageDto, signal
    },
      options);
    }
  


export const getConversationsControllerCreateProgramAMessageMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof conversationsControllerCreateProgramAMessage>>, TError,{applicationId: string;channel: string;data: CreateConversationMessageDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof conversationsControllerCreateProgramAMessage>>, TError,{applicationId: string;channel: string;data: CreateConversationMessageDto}, TContext> => {

const mutationKey = ['conversationsControllerCreateProgramAMessage'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof conversationsControllerCreateProgramAMessage>>, {applicationId: string;channel: string;data: CreateConversationMessageDto}> = (props) => {
          const {applicationId,channel,data} = props ?? {};

          return  conversationsControllerCreateProgramAMessage(applicationId,channel,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ConversationsControllerCreateProgramAMessageMutationResult = NonNullable<Awaited<ReturnType<typeof conversationsControllerCreateProgramAMessage>>>
    export type ConversationsControllerCreateProgramAMessageMutationBody = CreateConversationMessageDto
    export type ConversationsControllerCreateProgramAMessageMutationError = unknown

    export const useConversationsControllerCreateProgramAMessage = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof conversationsControllerCreateProgramAMessage>>, TError,{applicationId: string;channel: string;data: CreateConversationMessageDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof conversationsControllerCreateProgramAMessage>>,
        TError,
        {applicationId: string;channel: string;data: CreateConversationMessageDto},
        TContext
      > => {

      const mutationOptions = getConversationsControllerCreateProgramAMessageMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const conversationsControllerUpdateMessage = (
    messageId: string,
    updateConversationMessageDto: UpdateConversationMessageDto,
 options?: SecondParameter<typeof orvalMutator>,) => {
      
      
      return orvalMutator<ConversationMessageDto>(
      {url: `/conversations/messages/${messageId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateConversationMessageDto
    },
      options);
    }
  


export const getConversationsControllerUpdateMessageMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof conversationsControllerUpdateMessage>>, TError,{messageId: string;data: UpdateConversationMessageDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof conversationsControllerUpdateMessage>>, TError,{messageId: string;data: UpdateConversationMessageDto}, TContext> => {

const mutationKey = ['conversationsControllerUpdateMessage'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof conversationsControllerUpdateMessage>>, {messageId: string;data: UpdateConversationMessageDto}> = (props) => {
          const {messageId,data} = props ?? {};

          return  conversationsControllerUpdateMessage(messageId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ConversationsControllerUpdateMessageMutationResult = NonNullable<Awaited<ReturnType<typeof conversationsControllerUpdateMessage>>>
    export type ConversationsControllerUpdateMessageMutationBody = UpdateConversationMessageDto
    export type ConversationsControllerUpdateMessageMutationError = unknown

    export const useConversationsControllerUpdateMessage = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof conversationsControllerUpdateMessage>>, TError,{messageId: string;data: UpdateConversationMessageDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof conversationsControllerUpdateMessage>>,
        TError,
        {messageId: string;data: UpdateConversationMessageDto},
        TContext
      > => {

      const mutationOptions = getConversationsControllerUpdateMessageMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const conversationsControllerDeleteMessage = (
    messageId: string,
 options?: SecondParameter<typeof orvalMutator>,) => {
      
      
      return orvalMutator<ConversationMessageDto>(
      {url: `/conversations/messages/${messageId}`, method: 'DELETE'
    },
      options);
    }
  


export const getConversationsControllerDeleteMessageMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof conversationsControllerDeleteMessage>>, TError,{messageId: string}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof conversationsControllerDeleteMessage>>, TError,{messageId: string}, TContext> => {

const mutationKey = ['conversationsControllerDeleteMessage'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof conversationsControllerDeleteMessage>>, {messageId: string}> = (props) => {
          const {messageId} = props ?? {};

          return  conversationsControllerDeleteMessage(messageId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ConversationsControllerDeleteMessageMutationResult = NonNullable<Awaited<ReturnType<typeof conversationsControllerDeleteMessage>>>
    
    export type ConversationsControllerDeleteMessageMutationError = unknown

    export const useConversationsControllerDeleteMessage = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof conversationsControllerDeleteMessage>>, TError,{messageId: string}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof conversationsControllerDeleteMessage>>,
        TError,
        {messageId: string},
        TContext
      > => {

      const mutationOptions = getConversationsControllerDeleteMessageMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const conversationsControllerRequestAttachmentDownload = (
    messageId: string,
    attachmentId: string,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<ConversationAttachmentDownloadDto>(
      {url: `/conversations/messages/${messageId}/attachments/${attachmentId}/download`, method: 'POST', signal
    },
      options);
    }
  


export const getConversationsControllerRequestAttachmentDownloadMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof conversationsControllerRequestAttachmentDownload>>, TError,{messageId: string;attachmentId: string}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof conversationsControllerRequestAttachmentDownload>>, TError,{messageId: string;attachmentId: string}, TContext> => {

const mutationKey = ['conversationsControllerRequestAttachmentDownload'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof conversationsControllerRequestAttachmentDownload>>, {messageId: string;attachmentId: string}> = (props) => {
          const {messageId,attachmentId} = props ?? {};

          return  conversationsControllerRequestAttachmentDownload(messageId,attachmentId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ConversationsControllerRequestAttachmentDownloadMutationResult = NonNullable<Awaited<ReturnType<typeof conversationsControllerRequestAttachmentDownload>>>
    
    export type ConversationsControllerRequestAttachmentDownloadMutationError = unknown

    export const useConversationsControllerRequestAttachmentDownload = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof conversationsControllerRequestAttachmentDownload>>, TError,{messageId: string;attachmentId: string}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof conversationsControllerRequestAttachmentDownload>>,
        TError,
        {messageId: string;attachmentId: string},
        TContext
      > => {

      const mutationOptions = getConversationsControllerRequestAttachmentDownloadMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    