/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * NTI Backend
 * API for NTI platform workflows, authentication, and administrative operations.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CompleteUploadDto,
  DownloadUrlDto,
  FilesControllerRequestDownloadUrlParams,
  RequestUploadDto,
  UploadInstructionsDto,
  UploadedFileDto
} from '../index.schemas';

import { orvalMutator } from '../../api-client/openapi-runtime/runtime';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Creates a pending file record and returns a temporary presigned PUT URL for direct upload to Cloudflare R2.

Use this endpoint first. The returned uploadUrl is not a file preview link and it is not meant to be opened in the browser. It is a temporary signed storage URL that the frontend must call with an HTTP PUT request and the raw file bytes as the request body.

Frontend flow:
1. Call POST /files/upload-url with filename, mimeType, and size from the selected browser file.
2. Upload the file directly to the returned uploadUrl using fetch with method PUT, Content-Type equal to the file MIME type, and the file as the request body.
3. After the PUT request succeeds, call POST /files/complete with the returned fileId.

Important details:
- Send the file as a raw binary body. Do not wrap it in JSON.
- Do not use FormData for the presigned upload unless the backend explicitly signs a multipart form upload. This endpoint signs a PUT object upload, so FormData will change the payload and usually break the signature.
- Keep the Content-Type equal to the mimeType sent when requesting the URL.
- Upload before expiresAt, otherwise request a new URL.
- Set visibility to PUBLIC only for files that are intended to be publicly readable through a stable URL. Leave it as PRIVATE for protected documents such as audit PDFs.
 * @summary Request a presigned upload URL
 */
export const filesControllerRequestUploadUrl = (
    requestUploadDto: RequestUploadDto,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<UploadInstructionsDto>(
      {url: `/files/upload-url`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: requestUploadDto, signal
    },
      options);
    }
  


export const getFilesControllerRequestUploadUrlMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof filesControllerRequestUploadUrl>>, TError,{data: RequestUploadDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof filesControllerRequestUploadUrl>>, TError,{data: RequestUploadDto}, TContext> => {

const mutationKey = ['filesControllerRequestUploadUrl'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof filesControllerRequestUploadUrl>>, {data: RequestUploadDto}> = (props) => {
          const {data} = props ?? {};

          return  filesControllerRequestUploadUrl(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type FilesControllerRequestUploadUrlMutationResult = NonNullable<Awaited<ReturnType<typeof filesControllerRequestUploadUrl>>>
    export type FilesControllerRequestUploadUrlMutationBody = RequestUploadDto
    export type FilesControllerRequestUploadUrlMutationError = void

    /**
 * @summary Request a presigned upload URL
 */
export const useFilesControllerRequestUploadUrl = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof filesControllerRequestUploadUrl>>, TError,{data: RequestUploadDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof filesControllerRequestUploadUrl>>,
        TError,
        {data: RequestUploadDto},
        TContext
      > => {

      const mutationOptions = getFilesControllerRequestUploadUrlMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Returns a short-lived presigned GET URL for a file owned by the current user.

PRIVATE files receive a short-lived signed URL. PUBLIC files receive their stable public URL.

Frontend usage examples:
1. For previews: set an img src or iframe src to the returned downloadUrl.
2. For manual downloads: use the returned downloadUrl in an anchor element or call window.open(downloadUrl).
3. For custom handling: fetch the returned URL and read the response as a blob.

The URL is temporary. If it expires, request a new one.
 * @summary Request a presigned download URL
 */
export const filesControllerRequestDownloadUrl = (
    id: string,
    params?: FilesControllerRequestDownloadUrlParams,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<DownloadUrlDto>(
      {url: `/files/${id}/download-url`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getFilesControllerRequestDownloadUrlQueryKey = (id?: string,
    params?: FilesControllerRequestDownloadUrlParams,) => {
    return [
    `/files/${id}/download-url`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getFilesControllerRequestDownloadUrlQueryOptions = <TData = Awaited<ReturnType<typeof filesControllerRequestDownloadUrl>>, TError = void>(id: string,
    params?: FilesControllerRequestDownloadUrlParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerRequestDownloadUrl>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFilesControllerRequestDownloadUrlQueryKey(id,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof filesControllerRequestDownloadUrl>>> = ({ signal }) => filesControllerRequestDownloadUrl(id,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof filesControllerRequestDownloadUrl>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FilesControllerRequestDownloadUrlQueryResult = NonNullable<Awaited<ReturnType<typeof filesControllerRequestDownloadUrl>>>
export type FilesControllerRequestDownloadUrlQueryError = void


export function useFilesControllerRequestDownloadUrl<TData = Awaited<ReturnType<typeof filesControllerRequestDownloadUrl>>, TError = void>(
 id: string,
    params: undefined |  FilesControllerRequestDownloadUrlParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerRequestDownloadUrl>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof filesControllerRequestDownloadUrl>>,
          TError,
          Awaited<ReturnType<typeof filesControllerRequestDownloadUrl>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFilesControllerRequestDownloadUrl<TData = Awaited<ReturnType<typeof filesControllerRequestDownloadUrl>>, TError = void>(
 id: string,
    params?: FilesControllerRequestDownloadUrlParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerRequestDownloadUrl>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof filesControllerRequestDownloadUrl>>,
          TError,
          Awaited<ReturnType<typeof filesControllerRequestDownloadUrl>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFilesControllerRequestDownloadUrl<TData = Awaited<ReturnType<typeof filesControllerRequestDownloadUrl>>, TError = void>(
 id: string,
    params?: FilesControllerRequestDownloadUrlParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerRequestDownloadUrl>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Request a presigned download URL
 */

export function useFilesControllerRequestDownloadUrl<TData = Awaited<ReturnType<typeof filesControllerRequestDownloadUrl>>, TError = void>(
 id: string,
    params?: FilesControllerRequestDownloadUrlParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerRequestDownloadUrl>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFilesControllerRequestDownloadUrlQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Call this endpoint after the frontend successfully uploads the file bytes to the presigned uploadUrl.

This endpoint does not upload the file itself. It finalizes the pending file record created by POST /files/upload-url and marks it as uploaded.

Typical frontend sequence:
1. POST /files/upload-url
2. PUT uploadUrl with the raw File object
3. POST /files/complete with fileId and optionally size

If the upload URL expired, request a new one and repeat the flow.

 * @summary Mark uploaded file as complete
 */
export const filesControllerCompleteUpload = (
    completeUploadDto: CompleteUploadDto,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<UploadedFileDto>(
      {url: `/files/complete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: completeUploadDto, signal
    },
      options);
    }
  


export const getFilesControllerCompleteUploadMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof filesControllerCompleteUpload>>, TError,{data: CompleteUploadDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof filesControllerCompleteUpload>>, TError,{data: CompleteUploadDto}, TContext> => {

const mutationKey = ['filesControllerCompleteUpload'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof filesControllerCompleteUpload>>, {data: CompleteUploadDto}> = (props) => {
          const {data} = props ?? {};

          return  filesControllerCompleteUpload(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type FilesControllerCompleteUploadMutationResult = NonNullable<Awaited<ReturnType<typeof filesControllerCompleteUpload>>>
    export type FilesControllerCompleteUploadMutationBody = CompleteUploadDto
    export type FilesControllerCompleteUploadMutationError = void

    /**
 * @summary Mark uploaded file as complete
 */
export const useFilesControllerCompleteUpload = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof filesControllerCompleteUpload>>, TError,{data: CompleteUploadDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof filesControllerCompleteUpload>>,
        TError,
        {data: CompleteUploadDto},
        TContext
      > => {

      const mutationOptions = getFilesControllerCompleteUploadMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    