import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import { AppProviders } from 'components/providers';
import { activateDefaultLocale } from 'lib/i18n/runtime';
import { getRequestLocale } from 'lib/i18n/server-locale';

import './styles/global.css';
import { SpeedInsights } from '@vercel/speed-insights/next';

activateDefaultLocale();

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getRequestLocale();

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AppProviders>{children}</AppProviders>

        <SpeedInsights />
      </body>
    </html>
  );
}
