/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * NTI Backend
 * API for NTI platform workflows, authentication, and administrative operations.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  CreateSystemInviteDto,
  SystemInviteResponseDto
} from '../index.schemas';

import { orvalMutator } from '../../api-client/openapi-runtime/runtime';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Allows SUPER_ADMIN to invite ADMIN, MENTOR, and EVALUATOR; ADMIN can invite MENTOR and EVALUATOR only.
 * @summary Create system invitation
 */
export const adminCreateSystemInvite = (
    createSystemInviteDto: CreateSystemInviteDto,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<SystemInviteResponseDto>(
      {url: `/admin/invites`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createSystemInviteDto, signal
    },
      options);
    }
  


export const getAdminCreateSystemInviteMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateSystemInvite>>, TError,{data: CreateSystemInviteDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof adminCreateSystemInvite>>, TError,{data: CreateSystemInviteDto}, TContext> => {

const mutationKey = ['adminCreateSystemInvite'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminCreateSystemInvite>>, {data: CreateSystemInviteDto}> = (props) => {
          const {data} = props ?? {};

          return  adminCreateSystemInvite(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AdminCreateSystemInviteMutationResult = NonNullable<Awaited<ReturnType<typeof adminCreateSystemInvite>>>
    export type AdminCreateSystemInviteMutationBody = CreateSystemInviteDto
    export type AdminCreateSystemInviteMutationError = void

    /**
 * @summary Create system invitation
 */
export const useAdminCreateSystemInvite = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateSystemInvite>>, TError,{data: CreateSystemInviteDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminCreateSystemInvite>>,
        TError,
        {data: CreateSystemInviteDto},
        TContext
      > => {

      const mutationOptions = getAdminCreateSystemInviteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    