/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * NTI Backend
 * API for NTI platform workflows, authentication, and administrative operations.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AssignProgramBMentorDto,
  CompleteProgramBDocumentUploadDto,
  CreateProgramBFinalAcceptanceDto,
  CreateProgramBMentoringNoteDto,
  CreateProgramBMilestoneDto,
  CreateProgramBPoReviewDto,
  CreateProgramBProjectDocumentUploadDto,
  ProgramBDocumentDownloadDto,
  ProgramBMentoringNoteDto,
  ProgramBMilestoneDto,
  ProgramBPoReviewDto,
  ProgramBProjectDetailDto,
  ProgramBProjectDocumentDto,
  ProgramBProjectDocumentUploadDto,
  UpdateProgramBMilestoneDto
} from '../index.schemas';

import { orvalMutator } from '../../api-client/openapi-runtime/runtime';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const programBProjectsControllerListMy = (
    
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<ProgramBProjectDetailDto[]>(
      {url: `/program-b/projects/my`, method: 'GET', signal
    },
      options);
    }
  



export const getProgramBProjectsControllerListMyQueryKey = () => {
    return [
    `/program-b/projects/my`
    ] as const;
    }

    
export const getProgramBProjectsControllerListMyQueryOptions = <TData = Awaited<ReturnType<typeof programBProjectsControllerListMy>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBProjectsControllerListMy>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProgramBProjectsControllerListMyQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof programBProjectsControllerListMy>>> = ({ signal }) => programBProjectsControllerListMy(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof programBProjectsControllerListMy>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProgramBProjectsControllerListMyQueryResult = NonNullable<Awaited<ReturnType<typeof programBProjectsControllerListMy>>>
export type ProgramBProjectsControllerListMyQueryError = unknown


export function useProgramBProjectsControllerListMy<TData = Awaited<ReturnType<typeof programBProjectsControllerListMy>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBProjectsControllerListMy>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof programBProjectsControllerListMy>>,
          TError,
          Awaited<ReturnType<typeof programBProjectsControllerListMy>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProgramBProjectsControllerListMy<TData = Awaited<ReturnType<typeof programBProjectsControllerListMy>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBProjectsControllerListMy>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof programBProjectsControllerListMy>>,
          TError,
          Awaited<ReturnType<typeof programBProjectsControllerListMy>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProgramBProjectsControllerListMy<TData = Awaited<ReturnType<typeof programBProjectsControllerListMy>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBProjectsControllerListMy>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useProgramBProjectsControllerListMy<TData = Awaited<ReturnType<typeof programBProjectsControllerListMy>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBProjectsControllerListMy>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProgramBProjectsControllerListMyQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const programBProjectsControllerGetProject = (
    id: string,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<ProgramBProjectDetailDto>(
      {url: `/program-b/projects/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getProgramBProjectsControllerGetProjectQueryKey = (id?: string,) => {
    return [
    `/program-b/projects/${id}`
    ] as const;
    }

    
export const getProgramBProjectsControllerGetProjectQueryOptions = <TData = Awaited<ReturnType<typeof programBProjectsControllerGetProject>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBProjectsControllerGetProject>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProgramBProjectsControllerGetProjectQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof programBProjectsControllerGetProject>>> = ({ signal }) => programBProjectsControllerGetProject(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof programBProjectsControllerGetProject>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProgramBProjectsControllerGetProjectQueryResult = NonNullable<Awaited<ReturnType<typeof programBProjectsControllerGetProject>>>
export type ProgramBProjectsControllerGetProjectQueryError = unknown


export function useProgramBProjectsControllerGetProject<TData = Awaited<ReturnType<typeof programBProjectsControllerGetProject>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBProjectsControllerGetProject>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof programBProjectsControllerGetProject>>,
          TError,
          Awaited<ReturnType<typeof programBProjectsControllerGetProject>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProgramBProjectsControllerGetProject<TData = Awaited<ReturnType<typeof programBProjectsControllerGetProject>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBProjectsControllerGetProject>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof programBProjectsControllerGetProject>>,
          TError,
          Awaited<ReturnType<typeof programBProjectsControllerGetProject>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProgramBProjectsControllerGetProject<TData = Awaited<ReturnType<typeof programBProjectsControllerGetProject>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBProjectsControllerGetProject>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useProgramBProjectsControllerGetProject<TData = Awaited<ReturnType<typeof programBProjectsControllerGetProject>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBProjectsControllerGetProject>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProgramBProjectsControllerGetProjectQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const programBProjectsControllerListMilestones = (
    id: string,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<ProgramBMilestoneDto[]>(
      {url: `/program-b/projects/${id}/milestones`, method: 'GET', signal
    },
      options);
    }
  



export const getProgramBProjectsControllerListMilestonesQueryKey = (id?: string,) => {
    return [
    `/program-b/projects/${id}/milestones`
    ] as const;
    }

    
export const getProgramBProjectsControllerListMilestonesQueryOptions = <TData = Awaited<ReturnType<typeof programBProjectsControllerListMilestones>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBProjectsControllerListMilestones>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProgramBProjectsControllerListMilestonesQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof programBProjectsControllerListMilestones>>> = ({ signal }) => programBProjectsControllerListMilestones(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof programBProjectsControllerListMilestones>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProgramBProjectsControllerListMilestonesQueryResult = NonNullable<Awaited<ReturnType<typeof programBProjectsControllerListMilestones>>>
export type ProgramBProjectsControllerListMilestonesQueryError = unknown


export function useProgramBProjectsControllerListMilestones<TData = Awaited<ReturnType<typeof programBProjectsControllerListMilestones>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBProjectsControllerListMilestones>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof programBProjectsControllerListMilestones>>,
          TError,
          Awaited<ReturnType<typeof programBProjectsControllerListMilestones>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProgramBProjectsControllerListMilestones<TData = Awaited<ReturnType<typeof programBProjectsControllerListMilestones>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBProjectsControllerListMilestones>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof programBProjectsControllerListMilestones>>,
          TError,
          Awaited<ReturnType<typeof programBProjectsControllerListMilestones>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProgramBProjectsControllerListMilestones<TData = Awaited<ReturnType<typeof programBProjectsControllerListMilestones>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBProjectsControllerListMilestones>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useProgramBProjectsControllerListMilestones<TData = Awaited<ReturnType<typeof programBProjectsControllerListMilestones>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBProjectsControllerListMilestones>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProgramBProjectsControllerListMilestonesQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const programBProjectsControllerCreateMilestone = (
    id: string,
    createProgramBMilestoneDto: CreateProgramBMilestoneDto,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<void>(
      {url: `/program-b/projects/${id}/milestones`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createProgramBMilestoneDto, signal
    },
      options);
    }
  


export const getProgramBProjectsControllerCreateMilestoneMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof programBProjectsControllerCreateMilestone>>, TError,{id: string;data: CreateProgramBMilestoneDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof programBProjectsControllerCreateMilestone>>, TError,{id: string;data: CreateProgramBMilestoneDto}, TContext> => {

const mutationKey = ['programBProjectsControllerCreateMilestone'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof programBProjectsControllerCreateMilestone>>, {id: string;data: CreateProgramBMilestoneDto}> = (props) => {
          const {id,data} = props ?? {};

          return  programBProjectsControllerCreateMilestone(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ProgramBProjectsControllerCreateMilestoneMutationResult = NonNullable<Awaited<ReturnType<typeof programBProjectsControllerCreateMilestone>>>
    export type ProgramBProjectsControllerCreateMilestoneMutationBody = CreateProgramBMilestoneDto
    export type ProgramBProjectsControllerCreateMilestoneMutationError = unknown

    export const useProgramBProjectsControllerCreateMilestone = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof programBProjectsControllerCreateMilestone>>, TError,{id: string;data: CreateProgramBMilestoneDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof programBProjectsControllerCreateMilestone>>,
        TError,
        {id: string;data: CreateProgramBMilestoneDto},
        TContext
      > => {

      const mutationOptions = getProgramBProjectsControllerCreateMilestoneMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const programBProjectsControllerUpdateMilestone = (
    id: string,
    milestoneId: string,
    updateProgramBMilestoneDto: UpdateProgramBMilestoneDto,
 options?: SecondParameter<typeof orvalMutator>,) => {
      
      
      return orvalMutator<void>(
      {url: `/program-b/projects/${id}/milestones/${milestoneId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateProgramBMilestoneDto
    },
      options);
    }
  


export const getProgramBProjectsControllerUpdateMilestoneMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof programBProjectsControllerUpdateMilestone>>, TError,{id: string;milestoneId: string;data: UpdateProgramBMilestoneDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof programBProjectsControllerUpdateMilestone>>, TError,{id: string;milestoneId: string;data: UpdateProgramBMilestoneDto}, TContext> => {

const mutationKey = ['programBProjectsControllerUpdateMilestone'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof programBProjectsControllerUpdateMilestone>>, {id: string;milestoneId: string;data: UpdateProgramBMilestoneDto}> = (props) => {
          const {id,milestoneId,data} = props ?? {};

          return  programBProjectsControllerUpdateMilestone(id,milestoneId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ProgramBProjectsControllerUpdateMilestoneMutationResult = NonNullable<Awaited<ReturnType<typeof programBProjectsControllerUpdateMilestone>>>
    export type ProgramBProjectsControllerUpdateMilestoneMutationBody = UpdateProgramBMilestoneDto
    export type ProgramBProjectsControllerUpdateMilestoneMutationError = unknown

    export const useProgramBProjectsControllerUpdateMilestone = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof programBProjectsControllerUpdateMilestone>>, TError,{id: string;milestoneId: string;data: UpdateProgramBMilestoneDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof programBProjectsControllerUpdateMilestone>>,
        TError,
        {id: string;milestoneId: string;data: UpdateProgramBMilestoneDto},
        TContext
      > => {

      const mutationOptions = getProgramBProjectsControllerUpdateMilestoneMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const programBProjectsControllerListMentoringNotes = (
    id: string,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<ProgramBMentoringNoteDto[]>(
      {url: `/program-b/projects/${id}/mentoring-notes`, method: 'GET', signal
    },
      options);
    }
  



export const getProgramBProjectsControllerListMentoringNotesQueryKey = (id?: string,) => {
    return [
    `/program-b/projects/${id}/mentoring-notes`
    ] as const;
    }

    
export const getProgramBProjectsControllerListMentoringNotesQueryOptions = <TData = Awaited<ReturnType<typeof programBProjectsControllerListMentoringNotes>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBProjectsControllerListMentoringNotes>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProgramBProjectsControllerListMentoringNotesQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof programBProjectsControllerListMentoringNotes>>> = ({ signal }) => programBProjectsControllerListMentoringNotes(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof programBProjectsControllerListMentoringNotes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProgramBProjectsControllerListMentoringNotesQueryResult = NonNullable<Awaited<ReturnType<typeof programBProjectsControllerListMentoringNotes>>>
export type ProgramBProjectsControllerListMentoringNotesQueryError = unknown


export function useProgramBProjectsControllerListMentoringNotes<TData = Awaited<ReturnType<typeof programBProjectsControllerListMentoringNotes>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBProjectsControllerListMentoringNotes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof programBProjectsControllerListMentoringNotes>>,
          TError,
          Awaited<ReturnType<typeof programBProjectsControllerListMentoringNotes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProgramBProjectsControllerListMentoringNotes<TData = Awaited<ReturnType<typeof programBProjectsControllerListMentoringNotes>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBProjectsControllerListMentoringNotes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof programBProjectsControllerListMentoringNotes>>,
          TError,
          Awaited<ReturnType<typeof programBProjectsControllerListMentoringNotes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProgramBProjectsControllerListMentoringNotes<TData = Awaited<ReturnType<typeof programBProjectsControllerListMentoringNotes>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBProjectsControllerListMentoringNotes>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useProgramBProjectsControllerListMentoringNotes<TData = Awaited<ReturnType<typeof programBProjectsControllerListMentoringNotes>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBProjectsControllerListMentoringNotes>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProgramBProjectsControllerListMentoringNotesQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const programBProjectsControllerCreateMentoringNote = (
    id: string,
    createProgramBMentoringNoteDto: CreateProgramBMentoringNoteDto,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<void>(
      {url: `/program-b/projects/${id}/mentoring-notes`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createProgramBMentoringNoteDto, signal
    },
      options);
    }
  


export const getProgramBProjectsControllerCreateMentoringNoteMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof programBProjectsControllerCreateMentoringNote>>, TError,{id: string;data: CreateProgramBMentoringNoteDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof programBProjectsControllerCreateMentoringNote>>, TError,{id: string;data: CreateProgramBMentoringNoteDto}, TContext> => {

const mutationKey = ['programBProjectsControllerCreateMentoringNote'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof programBProjectsControllerCreateMentoringNote>>, {id: string;data: CreateProgramBMentoringNoteDto}> = (props) => {
          const {id,data} = props ?? {};

          return  programBProjectsControllerCreateMentoringNote(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ProgramBProjectsControllerCreateMentoringNoteMutationResult = NonNullable<Awaited<ReturnType<typeof programBProjectsControllerCreateMentoringNote>>>
    export type ProgramBProjectsControllerCreateMentoringNoteMutationBody = CreateProgramBMentoringNoteDto
    export type ProgramBProjectsControllerCreateMentoringNoteMutationError = unknown

    export const useProgramBProjectsControllerCreateMentoringNote = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof programBProjectsControllerCreateMentoringNote>>, TError,{id: string;data: CreateProgramBMentoringNoteDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof programBProjectsControllerCreateMentoringNote>>,
        TError,
        {id: string;data: CreateProgramBMentoringNoteDto},
        TContext
      > => {

      const mutationOptions = getProgramBProjectsControllerCreateMentoringNoteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const programBProjectsControllerListPoReviews = (
    id: string,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<ProgramBPoReviewDto[]>(
      {url: `/program-b/projects/${id}/po-reviews`, method: 'GET', signal
    },
      options);
    }
  



export const getProgramBProjectsControllerListPoReviewsQueryKey = (id?: string,) => {
    return [
    `/program-b/projects/${id}/po-reviews`
    ] as const;
    }

    
export const getProgramBProjectsControllerListPoReviewsQueryOptions = <TData = Awaited<ReturnType<typeof programBProjectsControllerListPoReviews>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBProjectsControllerListPoReviews>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProgramBProjectsControllerListPoReviewsQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof programBProjectsControllerListPoReviews>>> = ({ signal }) => programBProjectsControllerListPoReviews(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof programBProjectsControllerListPoReviews>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProgramBProjectsControllerListPoReviewsQueryResult = NonNullable<Awaited<ReturnType<typeof programBProjectsControllerListPoReviews>>>
export type ProgramBProjectsControllerListPoReviewsQueryError = unknown


export function useProgramBProjectsControllerListPoReviews<TData = Awaited<ReturnType<typeof programBProjectsControllerListPoReviews>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBProjectsControllerListPoReviews>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof programBProjectsControllerListPoReviews>>,
          TError,
          Awaited<ReturnType<typeof programBProjectsControllerListPoReviews>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProgramBProjectsControllerListPoReviews<TData = Awaited<ReturnType<typeof programBProjectsControllerListPoReviews>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBProjectsControllerListPoReviews>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof programBProjectsControllerListPoReviews>>,
          TError,
          Awaited<ReturnType<typeof programBProjectsControllerListPoReviews>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProgramBProjectsControllerListPoReviews<TData = Awaited<ReturnType<typeof programBProjectsControllerListPoReviews>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBProjectsControllerListPoReviews>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useProgramBProjectsControllerListPoReviews<TData = Awaited<ReturnType<typeof programBProjectsControllerListPoReviews>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBProjectsControllerListPoReviews>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProgramBProjectsControllerListPoReviewsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const programBProjectsControllerCreatePoReview = (
    id: string,
    createProgramBPoReviewDto: CreateProgramBPoReviewDto,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<void>(
      {url: `/program-b/projects/${id}/po-reviews`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createProgramBPoReviewDto, signal
    },
      options);
    }
  


export const getProgramBProjectsControllerCreatePoReviewMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof programBProjectsControllerCreatePoReview>>, TError,{id: string;data: CreateProgramBPoReviewDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof programBProjectsControllerCreatePoReview>>, TError,{id: string;data: CreateProgramBPoReviewDto}, TContext> => {

const mutationKey = ['programBProjectsControllerCreatePoReview'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof programBProjectsControllerCreatePoReview>>, {id: string;data: CreateProgramBPoReviewDto}> = (props) => {
          const {id,data} = props ?? {};

          return  programBProjectsControllerCreatePoReview(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ProgramBProjectsControllerCreatePoReviewMutationResult = NonNullable<Awaited<ReturnType<typeof programBProjectsControllerCreatePoReview>>>
    export type ProgramBProjectsControllerCreatePoReviewMutationBody = CreateProgramBPoReviewDto
    export type ProgramBProjectsControllerCreatePoReviewMutationError = unknown

    export const useProgramBProjectsControllerCreatePoReview = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof programBProjectsControllerCreatePoReview>>, TError,{id: string;data: CreateProgramBPoReviewDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof programBProjectsControllerCreatePoReview>>,
        TError,
        {id: string;data: CreateProgramBPoReviewDto},
        TContext
      > => {

      const mutationOptions = getProgramBProjectsControllerCreatePoReviewMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const programBProjectsControllerListDocuments = (
    id: string,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<ProgramBProjectDocumentDto[]>(
      {url: `/program-b/projects/${id}/documents`, method: 'GET', signal
    },
      options);
    }
  



export const getProgramBProjectsControllerListDocumentsQueryKey = (id?: string,) => {
    return [
    `/program-b/projects/${id}/documents`
    ] as const;
    }

    
export const getProgramBProjectsControllerListDocumentsQueryOptions = <TData = Awaited<ReturnType<typeof programBProjectsControllerListDocuments>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBProjectsControllerListDocuments>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProgramBProjectsControllerListDocumentsQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof programBProjectsControllerListDocuments>>> = ({ signal }) => programBProjectsControllerListDocuments(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof programBProjectsControllerListDocuments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProgramBProjectsControllerListDocumentsQueryResult = NonNullable<Awaited<ReturnType<typeof programBProjectsControllerListDocuments>>>
export type ProgramBProjectsControllerListDocumentsQueryError = unknown


export function useProgramBProjectsControllerListDocuments<TData = Awaited<ReturnType<typeof programBProjectsControllerListDocuments>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBProjectsControllerListDocuments>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof programBProjectsControllerListDocuments>>,
          TError,
          Awaited<ReturnType<typeof programBProjectsControllerListDocuments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProgramBProjectsControllerListDocuments<TData = Awaited<ReturnType<typeof programBProjectsControllerListDocuments>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBProjectsControllerListDocuments>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof programBProjectsControllerListDocuments>>,
          TError,
          Awaited<ReturnType<typeof programBProjectsControllerListDocuments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProgramBProjectsControllerListDocuments<TData = Awaited<ReturnType<typeof programBProjectsControllerListDocuments>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBProjectsControllerListDocuments>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useProgramBProjectsControllerListDocuments<TData = Awaited<ReturnType<typeof programBProjectsControllerListDocuments>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programBProjectsControllerListDocuments>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProgramBProjectsControllerListDocumentsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const programBProjectsControllerCreateDocumentUpload = (
    id: string,
    createProgramBProjectDocumentUploadDto: CreateProgramBProjectDocumentUploadDto,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<ProgramBProjectDocumentUploadDto>(
      {url: `/program-b/projects/${id}/documents/upload`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createProgramBProjectDocumentUploadDto, signal
    },
      options);
    }
  


export const getProgramBProjectsControllerCreateDocumentUploadMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof programBProjectsControllerCreateDocumentUpload>>, TError,{id: string;data: CreateProgramBProjectDocumentUploadDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof programBProjectsControllerCreateDocumentUpload>>, TError,{id: string;data: CreateProgramBProjectDocumentUploadDto}, TContext> => {

const mutationKey = ['programBProjectsControllerCreateDocumentUpload'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof programBProjectsControllerCreateDocumentUpload>>, {id: string;data: CreateProgramBProjectDocumentUploadDto}> = (props) => {
          const {id,data} = props ?? {};

          return  programBProjectsControllerCreateDocumentUpload(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ProgramBProjectsControllerCreateDocumentUploadMutationResult = NonNullable<Awaited<ReturnType<typeof programBProjectsControllerCreateDocumentUpload>>>
    export type ProgramBProjectsControllerCreateDocumentUploadMutationBody = CreateProgramBProjectDocumentUploadDto
    export type ProgramBProjectsControllerCreateDocumentUploadMutationError = unknown

    export const useProgramBProjectsControllerCreateDocumentUpload = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof programBProjectsControllerCreateDocumentUpload>>, TError,{id: string;data: CreateProgramBProjectDocumentUploadDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof programBProjectsControllerCreateDocumentUpload>>,
        TError,
        {id: string;data: CreateProgramBProjectDocumentUploadDto},
        TContext
      > => {

      const mutationOptions = getProgramBProjectsControllerCreateDocumentUploadMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const programBProjectsControllerCompleteDocumentUpload = (
    id: string,
    documentId: string,
    completeProgramBDocumentUploadDto: CompleteProgramBDocumentUploadDto,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<ProgramBProjectDocumentDto>(
      {url: `/program-b/projects/${id}/documents/${documentId}/complete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: completeProgramBDocumentUploadDto, signal
    },
      options);
    }
  


export const getProgramBProjectsControllerCompleteDocumentUploadMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof programBProjectsControllerCompleteDocumentUpload>>, TError,{id: string;documentId: string;data: CompleteProgramBDocumentUploadDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof programBProjectsControllerCompleteDocumentUpload>>, TError,{id: string;documentId: string;data: CompleteProgramBDocumentUploadDto}, TContext> => {

const mutationKey = ['programBProjectsControllerCompleteDocumentUpload'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof programBProjectsControllerCompleteDocumentUpload>>, {id: string;documentId: string;data: CompleteProgramBDocumentUploadDto}> = (props) => {
          const {id,documentId,data} = props ?? {};

          return  programBProjectsControllerCompleteDocumentUpload(id,documentId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ProgramBProjectsControllerCompleteDocumentUploadMutationResult = NonNullable<Awaited<ReturnType<typeof programBProjectsControllerCompleteDocumentUpload>>>
    export type ProgramBProjectsControllerCompleteDocumentUploadMutationBody = CompleteProgramBDocumentUploadDto
    export type ProgramBProjectsControllerCompleteDocumentUploadMutationError = unknown

    export const useProgramBProjectsControllerCompleteDocumentUpload = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof programBProjectsControllerCompleteDocumentUpload>>, TError,{id: string;documentId: string;data: CompleteProgramBDocumentUploadDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof programBProjectsControllerCompleteDocumentUpload>>,
        TError,
        {id: string;documentId: string;data: CompleteProgramBDocumentUploadDto},
        TContext
      > => {

      const mutationOptions = getProgramBProjectsControllerCompleteDocumentUploadMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const programBProjectsControllerRequestDocumentDownload = (
    id: string,
    documentId: string,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<ProgramBDocumentDownloadDto>(
      {url: `/program-b/projects/${id}/documents/${documentId}/download`, method: 'POST', signal
    },
      options);
    }
  


export const getProgramBProjectsControllerRequestDocumentDownloadMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof programBProjectsControllerRequestDocumentDownload>>, TError,{id: string;documentId: string}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof programBProjectsControllerRequestDocumentDownload>>, TError,{id: string;documentId: string}, TContext> => {

const mutationKey = ['programBProjectsControllerRequestDocumentDownload'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof programBProjectsControllerRequestDocumentDownload>>, {id: string;documentId: string}> = (props) => {
          const {id,documentId} = props ?? {};

          return  programBProjectsControllerRequestDocumentDownload(id,documentId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ProgramBProjectsControllerRequestDocumentDownloadMutationResult = NonNullable<Awaited<ReturnType<typeof programBProjectsControllerRequestDocumentDownload>>>
    
    export type ProgramBProjectsControllerRequestDocumentDownloadMutationError = unknown

    export const useProgramBProjectsControllerRequestDocumentDownload = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof programBProjectsControllerRequestDocumentDownload>>, TError,{id: string;documentId: string}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof programBProjectsControllerRequestDocumentDownload>>,
        TError,
        {id: string;documentId: string},
        TContext
      > => {

      const mutationOptions = getProgramBProjectsControllerRequestDocumentDownloadMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const programBProjectsControllerAssignMentor = (
    id: string,
    assignProgramBMentorDto: AssignProgramBMentorDto,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<ProgramBProjectDetailDto>(
      {url: `/program-b/projects/${id}/assign-mentor`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: assignProgramBMentorDto, signal
    },
      options);
    }
  


export const getProgramBProjectsControllerAssignMentorMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof programBProjectsControllerAssignMentor>>, TError,{id: string;data: AssignProgramBMentorDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof programBProjectsControllerAssignMentor>>, TError,{id: string;data: AssignProgramBMentorDto}, TContext> => {

const mutationKey = ['programBProjectsControllerAssignMentor'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof programBProjectsControllerAssignMentor>>, {id: string;data: AssignProgramBMentorDto}> = (props) => {
          const {id,data} = props ?? {};

          return  programBProjectsControllerAssignMentor(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ProgramBProjectsControllerAssignMentorMutationResult = NonNullable<Awaited<ReturnType<typeof programBProjectsControllerAssignMentor>>>
    export type ProgramBProjectsControllerAssignMentorMutationBody = AssignProgramBMentorDto
    export type ProgramBProjectsControllerAssignMentorMutationError = unknown

    export const useProgramBProjectsControllerAssignMentor = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof programBProjectsControllerAssignMentor>>, TError,{id: string;data: AssignProgramBMentorDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof programBProjectsControllerAssignMentor>>,
        TError,
        {id: string;data: AssignProgramBMentorDto},
        TContext
      > => {

      const mutationOptions = getProgramBProjectsControllerAssignMentorMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const programBProjectsControllerRecordFinalAcceptance = (
    id: string,
    createProgramBFinalAcceptanceDto: CreateProgramBFinalAcceptanceDto,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<void>(
      {url: `/program-b/projects/${id}/final-acceptance`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createProgramBFinalAcceptanceDto, signal
    },
      options);
    }
  


export const getProgramBProjectsControllerRecordFinalAcceptanceMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof programBProjectsControllerRecordFinalAcceptance>>, TError,{id: string;data: CreateProgramBFinalAcceptanceDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof programBProjectsControllerRecordFinalAcceptance>>, TError,{id: string;data: CreateProgramBFinalAcceptanceDto}, TContext> => {

const mutationKey = ['programBProjectsControllerRecordFinalAcceptance'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof programBProjectsControllerRecordFinalAcceptance>>, {id: string;data: CreateProgramBFinalAcceptanceDto}> = (props) => {
          const {id,data} = props ?? {};

          return  programBProjectsControllerRecordFinalAcceptance(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ProgramBProjectsControllerRecordFinalAcceptanceMutationResult = NonNullable<Awaited<ReturnType<typeof programBProjectsControllerRecordFinalAcceptance>>>
    export type ProgramBProjectsControllerRecordFinalAcceptanceMutationBody = CreateProgramBFinalAcceptanceDto
    export type ProgramBProjectsControllerRecordFinalAcceptanceMutationError = unknown

    export const useProgramBProjectsControllerRecordFinalAcceptance = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof programBProjectsControllerRecordFinalAcceptance>>, TError,{id: string;data: CreateProgramBFinalAcceptanceDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof programBProjectsControllerRecordFinalAcceptance>>,
        TError,
        {id: string;data: CreateProgramBFinalAcceptanceDto},
        TContext
      > => {

      const mutationOptions = getProgramBProjectsControllerRecordFinalAcceptanceMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    