/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * NTI Backend
 * API for NTI platform workflows, authentication, and administrative operations.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  AccountMessageResponseDto,
  ChangeEmailConfirmDto,
  ChangeEmailRequestDto,
  ChangePasswordDto
} from '../index.schemas';

import { orvalMutator } from '../../api-client/openapi-runtime/runtime';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Validates the current password, updates the password hash, and revokes all active refresh sessions for the authenticated user.
 * @summary Change my password
 */
export const changeMyPassword = (
    changePasswordDto: ChangePasswordDto,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<AccountMessageResponseDto>(
      {url: `/account/me/change-password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: changePasswordDto, signal
    },
      options);
    }
  


export const getChangeMyPasswordMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changeMyPassword>>, TError,{data: ChangePasswordDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof changeMyPassword>>, TError,{data: ChangePasswordDto}, TContext> => {

const mutationKey = ['changeMyPassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof changeMyPassword>>, {data: ChangePasswordDto}> = (props) => {
          const {data} = props ?? {};

          return  changeMyPassword(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ChangeMyPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof changeMyPassword>>>
    export type ChangeMyPasswordMutationBody = ChangePasswordDto
    export type ChangeMyPasswordMutationError = void

    /**
 * @summary Change my password
 */
export const useChangeMyPassword = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changeMyPassword>>, TError,{data: ChangePasswordDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof changeMyPassword>>,
        TError,
        {data: ChangePasswordDto},
        TContext
      > => {

      const mutationOptions = getChangeMyPasswordMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Creates or replaces a pending email-change token for the authenticated user and sends a confirmation link to the new email address.
 * @summary Request my email change
 */
export const requestMyEmailChange = (
    changeEmailRequestDto: ChangeEmailRequestDto,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<AccountMessageResponseDto>(
      {url: `/account/me/change-email/request`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: changeEmailRequestDto, signal
    },
      options);
    }
  


export const getRequestMyEmailChangeMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof requestMyEmailChange>>, TError,{data: ChangeEmailRequestDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof requestMyEmailChange>>, TError,{data: ChangeEmailRequestDto}, TContext> => {

const mutationKey = ['requestMyEmailChange'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof requestMyEmailChange>>, {data: ChangeEmailRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  requestMyEmailChange(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RequestMyEmailChangeMutationResult = NonNullable<Awaited<ReturnType<typeof requestMyEmailChange>>>
    export type RequestMyEmailChangeMutationBody = ChangeEmailRequestDto
    export type RequestMyEmailChangeMutationError = void

    /**
 * @summary Request my email change
 */
export const useRequestMyEmailChange = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof requestMyEmailChange>>, TError,{data: ChangeEmailRequestDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof requestMyEmailChange>>,
        TError,
        {data: ChangeEmailRequestDto},
        TContext
      > => {

      const mutationOptions = getRequestMyEmailChangeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Consumes a single-use email-change token, updates the authenticated user email, and revokes all active refresh sessions for that account.
 * @summary Confirm my email change
 */
export const confirmMyEmailChange = (
    changeEmailConfirmDto: ChangeEmailConfirmDto,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<AccountMessageResponseDto>(
      {url: `/account/me/change-email/confirm`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: changeEmailConfirmDto, signal
    },
      options);
    }
  


export const getConfirmMyEmailChangeMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof confirmMyEmailChange>>, TError,{data: ChangeEmailConfirmDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof confirmMyEmailChange>>, TError,{data: ChangeEmailConfirmDto}, TContext> => {

const mutationKey = ['confirmMyEmailChange'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof confirmMyEmailChange>>, {data: ChangeEmailConfirmDto}> = (props) => {
          const {data} = props ?? {};

          return  confirmMyEmailChange(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ConfirmMyEmailChangeMutationResult = NonNullable<Awaited<ReturnType<typeof confirmMyEmailChange>>>
    export type ConfirmMyEmailChangeMutationBody = ChangeEmailConfirmDto
    export type ConfirmMyEmailChangeMutationError = void

    /**
 * @summary Confirm my email change
 */
export const useConfirmMyEmailChange = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof confirmMyEmailChange>>, TError,{data: ChangeEmailConfirmDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof confirmMyEmailChange>>,
        TError,
        {data: ChangeEmailConfirmDto},
        TContext
      > => {

      const mutationOptions = getConfirmMyEmailChangeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    