/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * NTI Backend
 * API for NTI platform workflows, authentication, and administrative operations.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  RequestUniversityEmailDomainDto,
  UniversityEmailDomainControllerCheckParams
} from '../index.schemas';

import { orvalMutator } from '../../api-client/openapi-runtime/runtime';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const universityEmailDomainControllerListApproved = (
    
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<void>(
      {url: `/university-email-domains`, method: 'GET', signal
    },
      options);
    }
  



export const getUniversityEmailDomainControllerListApprovedQueryKey = () => {
    return [
    `/university-email-domains`
    ] as const;
    }

    
export const getUniversityEmailDomainControllerListApprovedQueryOptions = <TData = Awaited<ReturnType<typeof universityEmailDomainControllerListApproved>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof universityEmailDomainControllerListApproved>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUniversityEmailDomainControllerListApprovedQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof universityEmailDomainControllerListApproved>>> = ({ signal }) => universityEmailDomainControllerListApproved(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof universityEmailDomainControllerListApproved>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UniversityEmailDomainControllerListApprovedQueryResult = NonNullable<Awaited<ReturnType<typeof universityEmailDomainControllerListApproved>>>
export type UniversityEmailDomainControllerListApprovedQueryError = unknown


export function useUniversityEmailDomainControllerListApproved<TData = Awaited<ReturnType<typeof universityEmailDomainControllerListApproved>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof universityEmailDomainControllerListApproved>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof universityEmailDomainControllerListApproved>>,
          TError,
          Awaited<ReturnType<typeof universityEmailDomainControllerListApproved>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUniversityEmailDomainControllerListApproved<TData = Awaited<ReturnType<typeof universityEmailDomainControllerListApproved>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof universityEmailDomainControllerListApproved>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof universityEmailDomainControllerListApproved>>,
          TError,
          Awaited<ReturnType<typeof universityEmailDomainControllerListApproved>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUniversityEmailDomainControllerListApproved<TData = Awaited<ReturnType<typeof universityEmailDomainControllerListApproved>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof universityEmailDomainControllerListApproved>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useUniversityEmailDomainControllerListApproved<TData = Awaited<ReturnType<typeof universityEmailDomainControllerListApproved>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof universityEmailDomainControllerListApproved>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUniversityEmailDomainControllerListApprovedQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const universityEmailDomainControllerCheck = (
    params: UniversityEmailDomainControllerCheckParams,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<void>(
      {url: `/university-email-domains/check`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getUniversityEmailDomainControllerCheckQueryKey = (params?: UniversityEmailDomainControllerCheckParams,) => {
    return [
    `/university-email-domains/check`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getUniversityEmailDomainControllerCheckQueryOptions = <TData = Awaited<ReturnType<typeof universityEmailDomainControllerCheck>>, TError = unknown>(params: UniversityEmailDomainControllerCheckParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof universityEmailDomainControllerCheck>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUniversityEmailDomainControllerCheckQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof universityEmailDomainControllerCheck>>> = ({ signal }) => universityEmailDomainControllerCheck(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof universityEmailDomainControllerCheck>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UniversityEmailDomainControllerCheckQueryResult = NonNullable<Awaited<ReturnType<typeof universityEmailDomainControllerCheck>>>
export type UniversityEmailDomainControllerCheckQueryError = unknown


export function useUniversityEmailDomainControllerCheck<TData = Awaited<ReturnType<typeof universityEmailDomainControllerCheck>>, TError = unknown>(
 params: UniversityEmailDomainControllerCheckParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof universityEmailDomainControllerCheck>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof universityEmailDomainControllerCheck>>,
          TError,
          Awaited<ReturnType<typeof universityEmailDomainControllerCheck>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUniversityEmailDomainControllerCheck<TData = Awaited<ReturnType<typeof universityEmailDomainControllerCheck>>, TError = unknown>(
 params: UniversityEmailDomainControllerCheckParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof universityEmailDomainControllerCheck>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof universityEmailDomainControllerCheck>>,
          TError,
          Awaited<ReturnType<typeof universityEmailDomainControllerCheck>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUniversityEmailDomainControllerCheck<TData = Awaited<ReturnType<typeof universityEmailDomainControllerCheck>>, TError = unknown>(
 params: UniversityEmailDomainControllerCheckParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof universityEmailDomainControllerCheck>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useUniversityEmailDomainControllerCheck<TData = Awaited<ReturnType<typeof universityEmailDomainControllerCheck>>, TError = unknown>(
 params: UniversityEmailDomainControllerCheckParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof universityEmailDomainControllerCheck>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUniversityEmailDomainControllerCheckQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const universityEmailDomainControllerRequestDomain = (
    requestUniversityEmailDomainDto: RequestUniversityEmailDomainDto,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<void>(
      {url: `/university-email-domains/requests`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: requestUniversityEmailDomainDto, signal
    },
      options);
    }
  


export const getUniversityEmailDomainControllerRequestDomainMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof universityEmailDomainControllerRequestDomain>>, TError,{data: RequestUniversityEmailDomainDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof universityEmailDomainControllerRequestDomain>>, TError,{data: RequestUniversityEmailDomainDto}, TContext> => {

const mutationKey = ['universityEmailDomainControllerRequestDomain'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof universityEmailDomainControllerRequestDomain>>, {data: RequestUniversityEmailDomainDto}> = (props) => {
          const {data} = props ?? {};

          return  universityEmailDomainControllerRequestDomain(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UniversityEmailDomainControllerRequestDomainMutationResult = NonNullable<Awaited<ReturnType<typeof universityEmailDomainControllerRequestDomain>>>
    export type UniversityEmailDomainControllerRequestDomainMutationBody = RequestUniversityEmailDomainDto
    export type UniversityEmailDomainControllerRequestDomainMutationError = unknown

    export const useUniversityEmailDomainControllerRequestDomain = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof universityEmailDomainControllerRequestDomain>>, TError,{data: RequestUniversityEmailDomainDto}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof universityEmailDomainControllerRequestDomain>>,
        TError,
        {data: RequestUniversityEmailDomainDto},
        TContext
      > => {

      const mutationOptions = getUniversityEmailDomainControllerRequestDomainMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    