/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * NTI Backend
 * API for NTI platform workflows, authentication, and administrative operations.
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  FacultyLookupDto,
  ListUniversitiesParams,
  SpecializationLookupDto,
  UniversityLookupDto
} from '../index.schemas';

import { orvalMutator } from '../../api-client/openapi-runtime/runtime';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns universities filtered by optional search and activity flag.
 * @summary List universities
 */
export const listUniversities = (
    params?: ListUniversitiesParams,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<UniversityLookupDto[]>(
      {url: `/universities`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getListUniversitiesQueryKey = (params?: ListUniversitiesParams,) => {
    return [
    `/universities`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListUniversitiesQueryOptions = <TData = Awaited<ReturnType<typeof listUniversities>>, TError = void>(params?: ListUniversitiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUniversities>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListUniversitiesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listUniversities>>> = ({ signal }) => listUniversities(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listUniversities>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListUniversitiesQueryResult = NonNullable<Awaited<ReturnType<typeof listUniversities>>>
export type ListUniversitiesQueryError = void


export function useListUniversities<TData = Awaited<ReturnType<typeof listUniversities>>, TError = void>(
 params: undefined |  ListUniversitiesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUniversities>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listUniversities>>,
          TError,
          Awaited<ReturnType<typeof listUniversities>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListUniversities<TData = Awaited<ReturnType<typeof listUniversities>>, TError = void>(
 params?: ListUniversitiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUniversities>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listUniversities>>,
          TError,
          Awaited<ReturnType<typeof listUniversities>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListUniversities<TData = Awaited<ReturnType<typeof listUniversities>>, TError = void>(
 params?: ListUniversitiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUniversities>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List universities
 */

export function useListUniversities<TData = Awaited<ReturnType<typeof listUniversities>>, TError = void>(
 params?: ListUniversitiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUniversities>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListUniversitiesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Returns active faculties for the selected university.
 * @summary List faculties by university
 */
export const listFacultiesByUniversity = (
    universityId: string,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<FacultyLookupDto[]>(
      {url: `/universities/${universityId}/faculties`, method: 'GET', signal
    },
      options);
    }
  



export const getListFacultiesByUniversityQueryKey = (universityId?: string,) => {
    return [
    `/universities/${universityId}/faculties`
    ] as const;
    }

    
export const getListFacultiesByUniversityQueryOptions = <TData = Awaited<ReturnType<typeof listFacultiesByUniversity>>, TError = void>(universityId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFacultiesByUniversity>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListFacultiesByUniversityQueryKey(universityId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listFacultiesByUniversity>>> = ({ signal }) => listFacultiesByUniversity(universityId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(universityId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listFacultiesByUniversity>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListFacultiesByUniversityQueryResult = NonNullable<Awaited<ReturnType<typeof listFacultiesByUniversity>>>
export type ListFacultiesByUniversityQueryError = void


export function useListFacultiesByUniversity<TData = Awaited<ReturnType<typeof listFacultiesByUniversity>>, TError = void>(
 universityId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFacultiesByUniversity>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFacultiesByUniversity>>,
          TError,
          Awaited<ReturnType<typeof listFacultiesByUniversity>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFacultiesByUniversity<TData = Awaited<ReturnType<typeof listFacultiesByUniversity>>, TError = void>(
 universityId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFacultiesByUniversity>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFacultiesByUniversity>>,
          TError,
          Awaited<ReturnType<typeof listFacultiesByUniversity>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFacultiesByUniversity<TData = Awaited<ReturnType<typeof listFacultiesByUniversity>>, TError = void>(
 universityId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFacultiesByUniversity>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List faculties by university
 */

export function useListFacultiesByUniversity<TData = Awaited<ReturnType<typeof listFacultiesByUniversity>>, TError = void>(
 universityId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFacultiesByUniversity>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListFacultiesByUniversityQueryOptions(universityId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Returns active specializations for the selected faculty.
 * @summary List specializations by faculty
 */
export const listSpecializationsByFaculty = (
    facultyId: string,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {
      
      
      return orvalMutator<SpecializationLookupDto[]>(
      {url: `/faculties/${facultyId}/specializations`, method: 'GET', signal
    },
      options);
    }
  



export const getListSpecializationsByFacultyQueryKey = (facultyId?: string,) => {
    return [
    `/faculties/${facultyId}/specializations`
    ] as const;
    }

    
export const getListSpecializationsByFacultyQueryOptions = <TData = Awaited<ReturnType<typeof listSpecializationsByFaculty>>, TError = void>(facultyId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSpecializationsByFaculty>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSpecializationsByFacultyQueryKey(facultyId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listSpecializationsByFaculty>>> = ({ signal }) => listSpecializationsByFaculty(facultyId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(facultyId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listSpecializationsByFaculty>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListSpecializationsByFacultyQueryResult = NonNullable<Awaited<ReturnType<typeof listSpecializationsByFaculty>>>
export type ListSpecializationsByFacultyQueryError = void


export function useListSpecializationsByFaculty<TData = Awaited<ReturnType<typeof listSpecializationsByFaculty>>, TError = void>(
 facultyId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSpecializationsByFaculty>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSpecializationsByFaculty>>,
          TError,
          Awaited<ReturnType<typeof listSpecializationsByFaculty>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSpecializationsByFaculty<TData = Awaited<ReturnType<typeof listSpecializationsByFaculty>>, TError = void>(
 facultyId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSpecializationsByFaculty>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSpecializationsByFaculty>>,
          TError,
          Awaited<ReturnType<typeof listSpecializationsByFaculty>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSpecializationsByFaculty<TData = Awaited<ReturnType<typeof listSpecializationsByFaculty>>, TError = void>(
 facultyId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSpecializationsByFaculty>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List specializations by faculty
 */

export function useListSpecializationsByFaculty<TData = Awaited<ReturnType<typeof listSpecializationsByFaculty>>, TError = void>(
 facultyId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSpecializationsByFaculty>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListSpecializationsByFacultyQueryOptions(facultyId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




